### ISSUE TITLE
Trie root not found!

### ISSUE THREAD

**Issue by debris** [ethcore/parity#1212]
reported by @jacogr 

```
~ parity --testnet --rpc
2016-06-02 18:13:21 Using a conversion rate of Ξ1 = US$13.9 (17129155000 wei/gas)
2016-06-02 18:13:22 Starting Parity/v1.2.0-unstable-35753f2-20160602/x86_64-macos/rustc1.9.0
2016-06-02 18:13:22 Configured for Morden using "Ethash" engine
2016-06-02 18:13:22 Public node URL: enode://1f64f15db9f842087c938c6b1bcc2719595e1bd7fa9fc1dae38a89f31fce14cc67e50aa6e3939106ac987174100edab6fc50900716b970782c56aea4e2012c5a@0.0.0.0:30303
TrieDB::new(3f56…626f): Trie root not found!
thread 'hyper-server' panicked at 'Trie root not found!', util/src/trie/triedb.rs:64
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-06-02 18:13:30 Finishing work, please wait...
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Closed', ../src/libcore/result.rs:746
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x101670358 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:        0x101673975 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:        0x1016735ae - std::panicking::default_hook::haac48fa641db8fa2
   4:        0x10165dbd6 - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:        0x10165ea5e - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:        0x10166f627 - rust_begin_unwind
   7:        0x10169a920 - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:        0x10110a2b0 - core::result::unwrap_failed::h0bdd56634916bdf6
   9:        0x10110a112 - _<server..Listening as std..ops..Drop>::drop::hf7eefae0ab712359
  10:        0x10110a508 - hyper::server::Listening::close::h08ed0aabe12182f0
  11:        0x1010f1f3e - _<Server as std..ops..Drop>::drop::h612aedc21573f07e
  12:        0x100e1a1a7 - parity::execute_client::h93c52c469cd553fa
  13:        0x100e07eb4 - parity::execute::h4228f2b3aef67c46
  14:        0x100e063df - parity::main::hc0b8b9a4c77213f8
  15:        0x1016731a2 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
  16:        0x10166f5bb - __rust_try
  17:        0x101672fe4 - std::rt::lang_start::h5b0863080165c75e
thread panicked while panicking. aborting.
[1]    27726 illegal hardware instruction  parity --testnet --rpc
```

crashed by calling rpc method:

```
{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x63cf90d3f0410092fc0fca41846f596223979195","0x65432"],"id":6}
```

**Comment by jacogr** [comment]
Some more info -

1. parity run with `parity --testnet --rpc`
2. fully synced to testnet
3. was expecting error 32000 to come back
4. passing `blockNumber = 'latest'` works as expected

(From logs it is not RPC-related, but the more info, the better)

**Comment by rphmeier** [comment]
I just added support for non-latest block parameters in https://github.com/ethcore/parity/pull/1149, but it appears it still does not interact nicely with DB pruning. Have a fix in-progress.

**Comment by rphmeier** [comment]
Note that currently we can prune anything earlier than 1200 blocks before the best block's number, so even when the panicking is fixed, the request you are making will still (probably) be unsupported unless you are using the archive pruning option.

**Comment by jacogr** [comment]
100% happy with that, the E2E test was actually expecting a -32000 from Parity. I will also add the additional -1.2k blocks testcase (expecting success from all clients).

**Comment by jacogr** [comment]
Moving to 1,000 blocks before the current blockNumber does work as expected. (So it is only pruned-block-related.)

**Comment by rphmeier** [comment]
Hi @jacogr, I think I have fixed this issue. Please test against the PR branch to see if all is well.

**Comment by jacogr** [comment]
Perfect. Will let you know as soon as it has finished building.

**Comment by jacogr** [comment]
Brilliant, all my E2E tests are now ok for the `eth.getBalance` call - 

- correct balance with blockNumber = latest
- correct balance with blockNumber = latest - 1000
- error -32000 as expected with blockNumber = 0x65432
