### ISSUE TITLE
Exception in transaction queue

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#1307]
```
thread 'IO Worker #2' panicked at 'All transactions in `current` and `future` are always included in `by_hash`', ../src/libcore/option.rs:699
stack backtrace:
   1:     0x563d65dd50cf - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x563d65ddb2cb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x563d65ddaf4f - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x563d65dc11be - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   5:     0x563d65ddb511 - std::panicking::begin_panic::he426e15a3766089a
   6:     0x563d65dc22ba - std::panicking::begin_panic_fmt::hdddb415186c241e7
   7:     0x563d65ddb4ae - rust_begin_unwind
   8:     0x563d65e115af - core::panicking::panic_fmt::hf4e16cb7f0d41a25
   9:     0x563d65e18604 - core::option::expect_failed::hdb92832549f56a85
  10:     0x563d65a8fc8d - _<core..iter..Map<I, F> as core..iter..iterator..Iterator>::next::h1c1d9e98fe65de99
                        at ../src/libcore/option.rs:293
                        at ethcore/src/miner/transaction_queue.rs:578
                        at ../src/libcore/ops.rs:2009
                        at ../src/libcore/option.rs:385
                        at ../src/libcore/iter/mod.rs:762
                        at ../src/libcore/iter/mod.rs:762
  11:     0x563d65a7a42b - ethcore::miner::transaction_queue::TransactionQueue::top_transactions::hd08726b4c3730ebc
                        at ../src/libcollections/vec.rs:1417
                        at ../src/libcollections/vec.rs:1325
                        at ../src/libcore/iter/iterator.rs:1209
                        at ethcore/src/miner/transaction_queue.rs:576
  12:     0x563d65a7723d - ethcore::miner::miner::Miner::prepare_sealing::hd8594ed32b4a27f5
                        at ethcore/src/miner/miner.rs:108
  13:     0x563d659e7dbc - _<ethcore..miner..miner..Miner as ethcore..miner..MinerService>::update_sealing::hbf4a8c3ddbf7ec7a
                        at ethcore/src/miner/miner.rs:496
  14:     0x563d659af447 - _<ethcore..client..client..Client<V>>::import_verified_blocks::h06550255fdce1033
                        at ethcore/src/client/client.rs:357
  15:     0x563d659a8e24 - _<ethcore..service..ClientIoHandler as ethcore_util..io..IoHandler<ethcore_util..network..host..NetworkIoMessage<ethcore..service..SyncMessage>>>::message::h70ff49e72b96119c
                        at ethcore/src/service.rs:130
  16:     0x563d65985a78 - std::panicking::try::call::he1da3cbceecb89f0
                        at util/src/io/worker.rs:115
                        at util/src/io/worker.rs:95
                        at util/src/panics.rs:84
                        at ../src/libstd/panic.rs:251
                        at ../src/libstd/panicking.rs:272
  17:     0x563d65de558b - __rust_try
  18:     0x563d65de552e - __rust_maybe_catch_panic
  19:     0x563d65986d07 - _<F as alloc..boxed..FnBox<A>>::call_box::h7b58269ce3fa0479
                        at ../src/libstd/thread/local.rs:211
                        at ../src/libstd/panicking.rs:235
                        at ../src/libstd/panic.rs:307
                        at ../src/liballoc/boxed.rs:544
  20:     0x563d65dd99b4 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  21:     0x7f4d4f992183 - start_thread
  22:     0x7f4d501b837c - clone
  23:                0x0 - <unknown>
```

**Comment by HelixiR** [comment]
Fix that. -___-

**Comment by tomusdrw** [comment]
Unable to reproduce any more. Additional assertions in #1402 will give us more details if it happens again.
