### ISSUE TITLE
Crash on ctrl-c

### ISSUE THREAD

**Issue by debris** [ethcore/parity#1361]
```
cargo run -- --pruning fast
   Compiling parity v1.2.0 (file:///Users/marek/projects/ethcore/parity)
     Running `target/debug/parity --pruning fast`
Adding ver.lock
Executed 1 upgrade scripts - ok
2016-06-20 22:33:08 Using a conversion rate of Ξ1 = US$11.89 (20024828000 wei/gas)
2016-06-20 22:33:08 Starting Parity/v1.2.0-unstable-05583c2-20160620/x86_64-macos/rustc1.9.0
2016-06-20 22:33:08 Configured for Frontier/Homestead using "Ethash" engine
2016-06-20 22:33:08 Public node URL: enode://a8f0dd9c87bd54a864b070785a9a10425747cee30f664b509b2b74432f2e6ffcffd86381df0f71fa6b4de3f3459f9cbe2acf2ae1d8577d91e01400efe21f5582@0.0.0.0:30303
      #0 d4e5…8fa3      0 blk/s    0 tx/s   0 Mgas/s    6/ 7 peers         #0     0+    0 Qed      3 MiB db    6 KiB chain    2 KiB queue    7 KiB sync
      #0 d4e5…8fa3      0 blk/s    0 tx/s   0 Mgas/s    6/ 8 peers         #0     0+    0 Qed      3 MiB db    6 KiB chain    2 KiB queue    7 KiB sync
      #0 d4e5…8fa3      0 blk/s    0 tx/s   0 Mgas/s    2/ 4 peers         #0     0+    0 Qed      3 MiB db    6 KiB chain    2 KiB queue    7 KiB sync
      #0 d4e5…8fa3      0 blk/s    0 tx/s   0 Mgas/s    3/ 5 peers         #0     0+    0 Qed      3 MiB db    6 KiB chain    2 KiB queue    7 KiB sync
      #0 d4e5…8fa3      0 blk/s    0 tx/s   0 Mgas/s    4/ 6 peers         #0     0+    0 Qed      3 MiB db    6 KiB chain    2 KiB queue    7 KiB sync
     #11 3f5e…3242      2 blk/s    0 tx/s   0 Mgas/s    5/ 7 peers       #127   110+    0 Qed      3 MiB db   17 KiB chain  106 KiB queue   29 KiB sync
^C2016-06-20 22:33:50 Finishing work, please wait...

thread 'Verifier #5' panicked at 'Error sending BlockVerified message: Mio(Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("Network IO notification error") }) })', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10b6c1528 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:        0x10b6c63b5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:        0x10b6c5fee - std::panicking::default_hook::haac48fa641db8fa2
   4:        0x10b6ac126 - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:        0x10b6acfae - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:        0x10b6c07f7 - rust_begin_unwind
   7:        0x10b6ed370 - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:        0x10a7c49db - core::result::unwrap_failed::h66d45a2d77967d99
   9:        0x10a7c47f6 - _<std..result..Result<T, E>>::expect::h6e328140ca2bccc3
  10:        0x10a7c3fb6 - ethcore::block_queue::QueueSignal::set::hc782e91463719b28
  11:        0x10a7d2f8c - ethcore::block_queue::BlockQueue::verify::h67857048634af782
  12:        0x10a7d1ca8 - ethcore::block_queue::BlockQueue::new::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h4ceda3719a444255
  13:        0x10a7d1b38 - ethcore_util::panics::PanicHandler::catch_panic::h29bafdc58440ad82
  14:        0x10a7d1306 - ethcore::block_queue::BlockQueue::new::_$u7b$$u7b$closure$u7d$$u7d$::hc24eac63fd81967d
  15:        0x10a7d0bf9 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h587aedd7423d2e06
  16:        0x10a7d0b62 - std::sys_common::unwind::try::try_fn::h7924a6c54d2dc821
  17:        0x10b6c078b - __rust_try
  18:        0x10b6c0713 - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  19:        0x10a7d0aad - std::sys_common::unwind::try::h270a318278231503
  20:        0x10a7d08ae - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hfd623a8386c130fa
  21:        0x10a7d1650 - _<F as std..boxed..FnBox<A>>::call_box::h5fa27880d2bd7173
  22:        0x10b6c5548 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  23:     0x7fff93ad799c - _pthread_body
  24:     0x7fff93ad7919 - _pthread_start
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10b6c1528 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:        0x10b6c63b5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:        0x10b6c5fee - std::panicking::default_hook::haac48fa641db8fa2
   4:        0x10b6ac126 - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:        0x10b6acfae - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:        0x10b6c07f7 - rust_begin_unwind
   7:        0x10b6ed370 - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:        0x10a7d45d9 - core::result::unwrap_failed::h9c86ec60ab4970f7
   9:        0x10a7d4308 - _<std..result..Result<T, E>>::unwrap::h4c7238fd6d634df4
  10:        0x10a7d9c3a - ethcore::block_queue::BlockQueue::clear::h1243fc5f0ca189a9
  11:        0x10a7e6a6a - _<block_queue..BlockQueue as std..ops..Drop>::drop::h53a7d4fe3e5a9601
  12:        0x109edf06f - ethcore..block_queue..BlockQueue::drop.22750::h8c16d938c258aece
  13:        0x109ed491d - ethcore..client..Client::drop.22442::hbbc1e38a877827d4
  14:        0x109ed4853 - _<std..sync..Arc<T>>::drop_slow::hc667010a62eb7583
  15:        0x109ed4776 - _<std..sync..Arc<T> as std..ops..Drop>::drop::ha73dfe085cf03e83
  16:        0x109ed468d - std..sync..Arc<ethcore..client..Client>::drop.22439::h917575704704ec7c
  17:        0x109ec7766 - ethcore..service..ClientService::drop.21699::h82f95a0a75c55b27
  18:        0x109eb1c3a - parity::execute_client::h4ea25e4f35a5a6b8
  19:        0x109ea2eb6 - parity::execute::h4228f2b3aef67c46
  20:        0x109ea29b3 - parity::main::hc0b8b9a4c77213f8
  21:        0x10b6c5be2 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
  22:        0x10b6c078b - __rust_try
  23:        0x10b6c5a24 - std::rt::lang_start::h5b0863080165c75e
  24:        0x109ea3a59 - main
```

**Comment by Phaiax** [comment]
got the same one
