### ISSUE TITLE
Websockets module panics on Ctrl-C

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1462]
Apparently trips on a `debug_assert!`.

```
#1782561 353a…95b7      0 blk/s    0 tx/s   0 Mgas/s    1/ 9/25 peers   #1782561     0+    0 Qed     39 MiB db  117 KiB chain    2 KiB queue   10 KiB sync
^C2016-06-27 21:02:07 Finishing work, please wait...
thread '<unnamed>' panicked at 'Attempted to close connection while not yet open.', /Users/gav/.cargo/git/checkouts/ws-rs-7f5c42a366684f39/master/src/connection.rs:923
stack backtrace:

   1:        0x10a6d7dd8 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:        0x10a6dcac5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:        0x10a6dc6fe - std::panicking::default_hook::haac48fa641db8fa2
   4:        0x10a6c3816 - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:        0x1092b1f17 - std::sys_common::unwind::begin_unwind::hd78480d5ec5c51b2
   6:        0x1092f9bff - _<ws..connection..Connection<H>>::send_close::hc829d6099aed34ca
   7:        0x10930e436 - _<ws..connection..Connection<H>>::shutdown::h8bf88cb4b3e6a577
   8:        0x10930e2fa - _<ws..io..Handler<F>>::shutdown::h255b01386e2c81bd
   9:        0x109301e56 - _<ws..io..Handler<F> as mio..handler..Handler>::notify::he8ba1b6b0d0943d5
  10:        0x1093017a0 - _<mio..event_loop..EventLoop<H>>::notify::hd891245832a6a79e
  11:        0x1092d295b - _<mio..event_loop..EventLoop<H>>::run_once::h10ae73b4808f988a
  12:        0x1092d216c - _<mio..event_loop..EventLoop<H>>::run::h8066a47c5c7b0ea7
  13:        0x1092d1ea2 - _<ws..WebSocket<F>>::run::h6901ba000189eee4
  14:        0x1092d0975 - _<ws..WebSocket<F>>::listen::hff19bf74ecb43c4a
  15:        0x1092cfa0b - ethcore_signer::ws_server::Server::start::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h1c3892c366b564cb
  16:        0x1092cf80e - ethcore_util::panics::PanicHandler::catch_panic::h991e6aa47f1e2ead
  17:        0x1092cec77 - ethcore_signer::ws_server::Server::start::_$u7b$$u7b$closure$u7d$$u7d$::h17a0d68f886bf045
  18:        0x1092ce5cb - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::he0e0294eac3b1f1f
  19:        0x1092ce538 - std::sys_common::unwind::try::try_fn::hd00cc6afdd587ee9
  20:        0x10a6d703b - __rust_try
  21:        0x10a6d6fc3 - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  22:        0x1092ce475 - std::sys_common::unwind::try::hb25e968bfaf65fc4
  23:        0x1092ce231 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hc080255656a39a8e
➜  parity git:(idealpeers-in-log)   24:        0x1092cf2a7 - _<F as std..boxed..FnBox<A>>::call_box::hb0da033dff1cf6b9
  25:        0x10a6dbc58 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  26:     0x7fff99b0d99c - _pthread_body
  27:     0x7fff99b0d919 - _pthread_start
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10a6d7dd8 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:        0x10a6dcac5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:        0x10a6dc6fe - std::panicking::default_hook::haac48fa641db8fa2
   4:        0x10a6c3816 - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:        0x10a6c469e - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:        0x10a6d70a7 - rust_begin_unwind
   7:        0x10a703a80 - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:        0x1092cf6f4 - core::result::unwrap_failed::h0bdd56634916bdf6
   9:        0x1092cf4e1 - _<std..result..Result<T, E>>::unwrap::h960144839699913d
  10:        0x10931cd58 - _<ws_server..Server as std..ops..Drop>::drop::h4db441fdf602d46a
  11:        0x108ebf65c - ethcore_signer..Server::drop.24455::h116726a35d8593fe
  12:        0x108ebf61a - std..option..Option<ethcore_signer..Server>::drop.24452::h98f04bcdf8c48ac8
  13:        0x108ec5c80 - parity::wait_for_exit::h3cffa219eaba1aa4
  14:        0x108e739fe - parity::execute_client::hf1af7a2a1cc4f0af
  15:        0x108e63cde - parity::execute::h4228f2b3aef67c46
  16:        0x108e63773 - parity::main::hc0b8b9a4c77213f8
  17:        0x10a6dc2f2 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
  18:        0x10a6d703b - __rust_try
  19:        0x10a6dc134 - std::rt::lang_start::h5b0863080165c75e
  20:        0x108e64889 - main
```

**Comment by arkpar** [comment]
A debug assertion
https://github.com/ethcore/ws-rs/blob/master/src/connection.rs#L923
