### ISSUE TITLE
Error: Trie(InvalidStateRoot)

### ISSUE THREAD

**Issue by Cyberider** [ethcore/parity#1624]
Cause: The disk ran out of space during its first sync (I believe this was the cause).

These are the last 3 lines of normal operations just before the disk runs out of space, followed by the error:

```
#1392683 4d38…d57b      0 blk/s   87 tx/s   1 Mgas/s    1/25 peers   #1422771     0+30074 Qed     27 MiB db  225 KiB chain   23 MiB queue    1 MiB sync
#1392879 6db7…fb1a     39 blk/s  246 tx/s   5 Mgas/s    1/25 peers   #1422899     0+30010 Qed     28 MiB db   43 KiB chain   23 MiB queue    1 MiB sync
#1392884 4813…d7d3      0 blk/s  108 tx/s   2 Mgas/s    0/25 peers   #1422899     0+30010 Qed     30 MiB db  194 KiB chain   23 MiB queue    1 MiB sync
thread 'IO Worker #1' panicked at 'State DB commit failed.: SimpleString("IO error: /home/rick/.parity/906a34e69aec8c0d/v5.3-sec-overlayrecent/state/016951.log: No space left on device")', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-07-14 01:39:14 Finishing work, please wait...
2016-07-14 01:39:14 Stage 3 block verification failed for #1392890 (1a7a…1142)
Error: Block(UnknownParent(89cfbb5140aca503f228073252e8d02b272570e3041d51383e751b10c5fe6105))

```

![image](https://cloud.githubusercontent.com/assets/12577711/16846914/4303a30a-49a3-11e6-9966-f1781cc67218.png)

So yeah, I increase the size of the disk logical volume but parity cannot self-recover from this error so now I get this:

```
2016-07-14 08:40:53 Starting Parity/v1.2.1-beta/x86_64-linux-gnu/rustc1.9.0
2016-07-14 08:40:53 Using a conversion rate of Ξ1 = US$10.92 (21803594000 wei/gas)
2016-07-14 08:40:53 Error parsing node table file: SyntaxError("EOF While parsing string", 24, 144)
2016-07-14 08:40:53 Configured for Frontier/Homestead using Ethash engine
2016-07-14 08:40:53 Public node URL: enode://495e4416fe91d0a9d8924a1f77d832fe194a3ef3ab23649cea600101891a49efa28084e1b04166a468100ef0254a4bb59225cf5a2f180b0890a759c34a4f2c4a@0.0.0.0:30303
2016-07-14 08:41:02 Block import failed for #1392885 (cf1d…f9b0)
Error: Trie(InvalidStateRoot)
#1392884 4813…d7d3      0 blk/s    0 tx/s   0 Mgas/s    4/ 4 peers   #1392884     0+    0 Qed     23 MiB db  241 KiB chain  106 KiB queue   47 KiB sync
2016-07-14 08:41:06 Bad header 1393012 (15fa…6ba0) from 21: Geth/v1.4.8-stable/linux/go1.6.2, state = ChainHead
#1392884 4813…d7d3      0 blk/s    0 tx/s   0 Mgas/s    3/ 3 peers   #1392884     0+    0 Qed     23 MiB db  241 KiB chain    2 KiB queue   47 KiB sync
#1392884 4813…d7d3      0 blk/s    0 tx/s   0 Mgas/s    2/ 2 peers   #1392884     0+    0 Qed     23 MiB db  241 KiB chain    2 KiB queue   47 KiB sync
#1392884 4813…d7d3      0 blk/s    0 tx/s   0 Mgas/s    0/ 1 peers   #1392884     0+    0 Qed     23 MiB db  244 KiB chain    2 KiB queue   47 KiB sync
#1392884 4813…d7d3      0 blk/s    0 tx/s   0 Mgas/s    1/ 3 peers   #1392884     0+    0 Qed     23 MiB db  244 KiB chain    2 KiB queue   47 KiB sync
thread 'IO Worker #0' panicked at 'State root of best block header always valid.: InvalidStateRoot', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-07-14 08:41:26 Finishing work, please wait...
thread 'IO Worker #2' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
thread 'IO Worker #1' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
thread 'IO Worker #3' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
```
![image](https://cloud.githubusercontent.com/assets/12577711/16846958/7c6c5bbe-49a3-11e6-9db4-2e383a24328e.png)

So how do I recover without removing/reinstalling parity?

**Comment by rphmeier** [comment]
If your disk ran out of space, there are going to be certain blocks and state entries that are expected to be in the database but are not. Resuming a sync from a broken database cannot get these blocks again.

As far as I know, the only way to fix it is to delete your database (stored by default in `$HOME/.parity/906...`) and do a re-sync.

**Comment by Cyberider** [comment]
@rphmeier that worked thank you :-)

**Comment by arkpar** [comment]
Follow up issue: #1625
