### ISSUE TITLE
Unable to sync with v1.3.0-unstable-22a87b1-20160726/

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#1726]
When using the release "v1.3.0-unstable-22a87b1-20160726/" it eventually stopping syncing. Was previously using "parity-1.2.2-install-win64.exe" and had not problems with the synch 

-------------------------------------------------
C:\Users\MT4\.cargo\bin>parity --tracing on
2016-07-26 19:22:56 Starting Parity/v1.3.0-unstable-22a87b1-20160726/x86_64-windows-msvc/rustc1.10.0
2016-07-26 19:22:56 Using state DB journalling strategy fast
2016-07-26 19:22:57 Configured for Frontier/Homestead using Ethash engine
2016-07-26 19:22:57 Public node URL: enode://7c81c7305c075e81399897e500099565e733cfb67e7c2034c7b52fc73b769bd832f6c29d31c07541c57d083b8d1f01228a01257fa794c87bea36a7c2bf99a771@127.0.0.1:30303
2016-07-26 19:23:07 Syncing #1955257 5df6.5648      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #1955257    1/ 7/25 peers     42 MiB db  230 KiB chain    2 KiB queue    8 KiB sync
2016-07-26 19:23:18 Syncing #1955257 5df6.5648      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #1955257    1/ 7/25 peers     42 MiB db    3 MiB chain    2 KiB queue    8 KiB sync
2016-07-26 19:23:33 Syncing #1955383 2638.3f26      8 blk/s   94 tx/s   2 Mgas/s       0+    0 Qed   #1955383    1/10/25 peers     43 MiB db    4 MiB chain  187 KiB queue   29 KiB sync
2016-07-26 19:23:36 Imported #1955564 d5b6.6ca4 (48 txs, 1.20 Mgas, 107.12 ms, 6.15 KiB) + another 32 block(s)
2016-07-26 19:23:54 Imported #1955565 e269.166a (1 txs, 0.02 Mgas, 1.00 ms, 0.62 KiB)
2016-07-26 19:24:03     0/13/25 peers     43 MiB db   13 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:24:33     0/11/25 peers     43 MiB db    8 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:25:04     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:25:34     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:26:05     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:26:35     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:27:06     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:27:36     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:28:06     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:28:37     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:29:07     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:29:37     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:30:12     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:30:43     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:31:13     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:31:44     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:32:14     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:32:49     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:33:20     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:33:50     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:34:20     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:34:51     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:35:21     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:35:51     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:36:22     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:36:52     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:37:23     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:37:53     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:38:24     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:38:54     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:39:24     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:39:54     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:40:25     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:40:56     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:41:26     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:41:57     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:42:27     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:42:58     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:43:29     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:43:59     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:44:30     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:45:00     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:45:30     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:46:00     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:46:31     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:47:01     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:47:31     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:48:02     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:48:32     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync
2016-07-26 19:49:03     0/ 8/25 peers     43 MiB db    5 MiB chain    2 KiB queue   29 KiB sync

**Comment by arkpar** [comment]
Windows only. IO events just stop arriving suddenly.

**Comment by mtbitcoin** [comment]
just noticed that its also happening on 1.2.2 just not as frequently.

**Comment by arkpar** [comment]
@mtbitcoin Could you check again using the latest master?

**Comment by mtbitcoin** [comment]
@arkpar so far its looking good. Will update once i have re-traced every single transaction

**Comment by mtbitcoin** [comment]
@arkpar this might not be directly related to the sync, but it now crashes when attempting to trace_transaction for txhash 0x7140646443cfc3b0c041d26e7a2cfee903ba4ca80babf706aee61580655583c5

-----------------------------------
C:\Users\MT4\.cargo\bin>parity.exe --tracing on --jsonrpc-port 8546
2016-07-28 00:35:09 Starting Parity/v1.3.0-unstable-edda0b2-20160727/x86_64-windows-msvc/rustc1.10.0
2016-07-28 00:35:09 Using state DB journalling strategy fast
2016-07-28 00:35:10 Configured for Frontier/Homestead using Ethash engine
2016-07-28 00:35:15 Public node URL: enode://7c81c7305c075e81399897e500099565e733cfb67e7c2034c7b52fc73b769bd832f6c29d31c07541c57d083b8d1f01228a01257fa794c87bea36a7c2bf99a771@127.0.0.1:30303
thread '<unnamed>' panicked at 'DecodeError: RlpIsTooShort', Users\MT4\.cargo\git\checkouts\parity-6ba620efeffb2216\master\util\src\rlp\rlpin.rs:119
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-07-28 00:35:22 Finishing work, please wait...
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Closed', ../src/libcore\result.rs:785

**Comment by mtbitcoin** [comment]
also upgrading the DB is to version 8 from version 6 fails. From version 7 to 8 works though

C:\>parity export bc
Migrating database from version 6 to 8
Database migration unexpectedly failed

**Comment by mtbitcoin** [comment]
yup, looking good for the last 7 hours. Will reopen if this changes
