### ISSUE TITLE
Crash on transaction_trace

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1746]
crashes when attempting to trace_transaction for txhash 0x7140646443cfc3b0c041d26e7a2cfee903ba4ca80babf706aee61580655583c5

```
C:\Users\xx.cargo\bin>parity.exe --tracing on --jsonrpc-port 8546
2016-07-28 00:35:09 Starting Parity/v1.3.0-unstable-edda0b2-20160727/x86_64-windows-msvc/rustc1.10.0
2016-07-28 00:35:09 Using state DB journalling strategy fast
2016-07-28 00:35:10 Configured for Frontier/Homestead using Ethash engine
2016-07-28 00:35:15 Public node URL: enode://7c81c7305c075e81399897e500099565e733cfb67e7c2034c7b52fc73b769bd832f6c29d31c07541c57d083b8d1f01228a01257fa794c87bea36a7c2bf99a771@127.0.0.1:30303
thread '' panicked at 'DecodeError: RlpIsTooShort', Users\MT4.cargo\git\checkouts\parity-6ba620efeffb2216\master\util\src\rlp\rlpin.rs:119
note: Run with RUST_BACKTRACE=1 for a backtrace.
2016-07-28 00:35:22 Finishing work, please wait...
thread '

' panicked at 'called Result::unwrap() on an Err value: Closed', ../src/libcore\result.rs:785
```

**Comment by gavofyork** [comment]
Duplicate of #1704
