### ISSUE TITLE
CLI Account New does not work on Windows

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#1808]
latest master, win 7
```
$ ./target/release/parity.exe account new
Please note that password is NOT RECOVERABLE.
Type password:
Repeat password:
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: SStore(Io(Error { repr: Os { code: 123, message: "The filename, directory name, or volume label syntax is incorrect." } }))', ../src/libcore\result.rs:785
stack backtrace:
   0:        0x140639062 - std::rt::lang_start::hbcefdc316c2fbd45
   1:        0x14063864d - std::rt::lang_start::hbcefdc316c2fbd45
   2:        0x1406183cd - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   3:        0x14063b40b - rust_begin_unwind
   4:        0x14061984f - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   5:        0x14063b04c - rust_begin_unwind
   6:        0x14063f295 - core::panicking::panic_fmt::h93df64e7370b5253
   7:        0x13feb807c - unwrap_failed<ethcore::account_provider::Error>
                        at c:\parity\src\libcore\macros.rs:29
   8:        0x13fcb7598 - execute
                        at c:\parity\src\libcore\result.rs:723
   9:        0x13fd33392 - main
                        at c:\parity\parity\parity\main.rs:113
  10:        0x14063802c - std::rt::lang_start::hbcefdc316c2fbd45
  11:        0x14063e7d1 - _rust_maybe_catch_panic
  12:        0x140637d64 - std::rt::lang_start::hbcefdc316c2fbd45
  13:        0x1407e5777 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264
  14:         0x76e75a4c - BaseThreadInitThunk

```

**Comment by tomusdrw** [comment]
Seems that creating new account over RPC is also broken.
