### ISSUE TITLE
Overflow in traces (debug mode)

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#1933]
Panic when syncing homestead using debug build
```
thread 'IO Worker #3' panicked at 'attempted to subtract with overflow', ethcore/src/trace/executive_tracer.rs:60
stack backtrace:
   1:     0x55d7acc75ecd - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
   2:     0x55d7acc7e601 - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
   3:     0x55d7acc7d449 - std::panicking::default_hook::hbbe7fa36a995aca0
   4:     0x55d7acc7daba - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   5:     0x55d7acc7d972 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
   6:     0x55d7acc7d8a0 - std::panicking::begin_panic_fmt::h20f5943904e5791d
   7:     0x55d7acc7d821 - rust_begin_unwind
   8:     0x55d7accba99c - core::panicking::panic_fmt::h19323e466869c656
   9:     0x55d7accba8cb - core::panicking::panic::hbfac80217e56ecbe
  10:     0x55d7ac095b0e - ethcore::trace::executive_tracer::update_trace_address::_{{closure}}::hab0e21f1ac2d81be
                        at /home/tomusdrw/eth/parity/ethcore/src/trace/executive_tracer.rs:60
  11:     0x55d7abcc07f5 - core::ops::impls::_<impl core..ops..FnOnce<A> for &'a mut F>::call_once::h7034d0d4dde601cc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/ops.rs:1988
  12:     0x55d7abab6f9b - _<core..option..Option<T>>::map::h0308a88f7a75fab4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:386
  13:     0x55d7abe87605 - _<core..iter..Map<I, F> as core..iter..iterator..Iterator>::next::hd6e3fa7434816ae0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/iter/mod.rs:899
  14:     0x55d7abb1762e - _<collections..vec..Vec<T>>::extend_desugared::hd1ac86d19de33da1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcollections/vec.rs:1496
  15:     0x55d7abec8ec0 - _<collections..vec..Vec<T> as core..iter..traits..FromIterator<T>>::from_iter::h238a866d5afe5b0f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcollections/vec.rs:1404
  16:     0x55d7abce5e92 - core::iter::iterator::Iterator::collect::h38ab5afc2eac3635
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/iter/iterator.rs:1207
  17:     0x55d7abf6d88d - ethcore::trace::executive_tracer::update_trace_address::h9a685404c8e379b4
                        at /home/tomusdrw/eth/parity/ethcore/src/trace/executive_tracer.rs:53
  18:     0x55d7abf6e21a - _<ethcore..trace..executive_tracer..ExecutiveTracer as ethcore..trace..Tracer>::trace_call::h71d4eaf06473f7cd
                        at /home/tomusdrw/eth/parity/ethcore/src/trace/executive_tracer.rs:95
  19:     0x55d7abff86bd - ethcore::executive::Executive::call::hac88c5d7dbcbc3f8
                        at /home/tomusdrw/eth/parity/ethcore/src/executive.rs:316
  20:     0x55d7abfede43 - ethcore::executive::Executive::transact_with_tracer::h46b89ba61a63863c
                        at /home/tomusdrw/eth/parity/ethcore/src/executive.rs:197
  21:     0x55d7abfe9579 - ethcore::executive::Executive::transact::h68c590b0eeead3a5
                        at /home/tomusdrw/eth/parity/ethcore/src/executive.rs:103
  22:     0x55d7abfddec6 - ethcore::state::State::apply::he0c7aa6e8d3f2fd0
                        at /home/tomusdrw/eth/parity/ethcore/src/state.rs:238
  23:     0x55d7abf2c5b2 - ethcore::block::OpenBlock::push_transaction::h8b9d3b463a32cb16
                        at /home/tomusdrw/eth/parity/ethcore/src/block.rs:335
  24:     0x55d7abf2fa8b - ethcore::block::enact::h9511c2de584b95d8
                        at /home/tomusdrw/eth/parity/ethcore/src/block.rs:521
  25:     0x55d7abf303be - ethcore::block::enact_verified::hf1a7469fba8c5367
                        at /home/tomusdrw/eth/parity/ethcore/src/block.rs:556
  26:     0x55d7abf3c302 - ethcore::client::client::Client::check_and_close_block::hd4ea71d3bb4e356a
                        at /home/tomusdrw/eth/parity/ethcore/src/client/client.rs:303
  27:     0x55d7abf3d811 - ethcore::client::client::Client::import_verified_blocks::h40de2a89a5a0418a
                        at /home/tomusdrw/eth/parity/ethcore/src/client/client.rs:364
  28:     0x55d7abf6a744 - _<ethcore..service..ClientIoHandler as ethcore_io..IoHandler<ethcore..service..ClientIoMessage>>::message::he153888e196df949
                        at /home/tomusdrw/eth/parity/ethcore/src/service.rs:160
  29:     0x55d7ab9c5c1a - ethcore_io::worker::Worker::do_work::h7bc60be54b2e1a8c
                        at /home/tomusdrw/eth/parity/util/io/src/worker.rs:117
  30:     0x55d7ab9c618e - ethcore_io::worker::Worker::work_loop::h1a67e56b9ef80204
                        at /home/tomusdrw/eth/parity/util/io/src/worker.rs:97
  31:     0x55d7ac062a09 - ethcore_io::worker::Worker::new::_{{closure}}::_{{closure}}::hee71a93cfc736d0b
  32:     0x55d7ab9c4dda - ethcore_io::panics::PanicHandler::catch_panic::hbde4e755ba2ce1ad
                        at /home/tomusdrw/eth/parity/util/io/src/panics.rs:85
  33:     0x55d7ac062d76 - ethcore_io::worker::Worker::new::_{{closure}}::h97a052efd6386d7c
  34:     0x55d7abec4e98 - _<std..panic..AssertUnwindSafe<F> as core..ops..FnOnce<()>>::call_once::hbea6983b886e5c81
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:256
  35:     0x55d7ac087dc1 - std::panicking::try::_{{closure}}::_{{closure}}::h87dfe8f5f9d6aa12
  36:     0x55d7abb74b3c - std::panicking::try::call::h258a09545dbbaab6
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:282
  37:     0x55d7acc86106 - __rust_maybe_catch_panic
  38:     0x55d7ac087cde - std::panicking::try::_{{closure}}::hc383e11f6df8284e
  39:     0x55d7abba2245 - _<std..thread..local..LocalKey<T>>::with::h78cb39935bdb5a1d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
  40:     0x55d7abb73f9e - std::panicking::try::h52bd8252f0bd41d1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:245
  41:     0x55d7abb6c3bf - std::panic::catch_unwind::h9f3c8e8f7780ef0b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:312
  42:     0x55d7ac086cdd - std::thread::Builder::spawn::_{{closure}}::h85041f4d4bdd266f
  43:     0x55d7abd14c55 - _<F as alloc..boxed..FnBox<A>>::call_box::h6689df0142e5f216
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:587
  44:     0x55d7acc7bfe2 - std::sys::thread::Thread::new::thread_start::h8f3bd45211e9f5ea
  45:     0x7f917b4ec183 - start_thread
  46:     0x7f917bf1637c - clone
  47:                0x0 - <unknown>
2016-08-16 10:32:44 Finishing work, please wait...
2016-08-16 10:32:44 Stage 3 block verification failed for #465219 (4fc5…2a00)
Error: Block(UnknownParent(29aff8f57364cc243d57de83146e03356cda552f766d12b6d1d048cd38636b6d))
```

**Comment by gavofyork** [comment]
[looks like](https://github.com/ethcore/parity/blame/master/ethcore/src/trace/executive_tracer.rs) that's @debris 's code.

at the least it needs an assertion with a proof since it's non-obvious why it should not underflow.
