### ISSUE TITLE
Slow I/O can cause crashe

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1942]
> ```
2016-08-09 22:13:47 UTCINFO:import: Imported #2042660 83ae…e007 (0 txs, 0.00 Mgas, 1.05 ms, 0.51 KiB)                                                                          [0/1994]
thread 'IO Worker #1' panicked at 'State DB commit failed.: SimpleString("IO error: /home/user/.parity/906a34e69aec8c0d/v5.3-sec-archive/state/016295.sst: Input/output error")
', ../src/libcore/result.rs:785
stack backtrace:
   1:       0x2b360e9c3f - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:       0x2b360efe7b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:       0x2b360efb03 - std::panicking::default_hook::hf3839060ccbb8764
   4:       0x2b360d53dd - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:       0x2b360f00c1 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:       0x2b360d64da - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:       0x2b360f005e - rust_begin_unwind
   8:       0x2b3612616f - core::panicking::panic_fmt::h93df64e7370b5253
   9:       0x2b35a56e4e - core::result::unwrap_failed::h377e324fb205cbf0
2016-08-09 22:14:01 UTCINFO:import:     0/ 3/25 peers      2 KiB db    6 MiB chain    2 KiB queue   13 KiB sync
                        at ../src/libcore/macros.rs:29
  10:       0x2b35a5b2eb - ethcore::client::client::Client::import_verified_blocks::h73d089ae6fba7c4a
                        at ../src/libcore/result.rs:747
                        at ethcore/src/client/client.rs:441
                        at ethcore/src/client/client.rs:374
  11:       0x2b35ac736a - std::panicking::try::call::hd668f89cb60f4fce
                        at util/src/io/worker.rs:117
                        at util/src/io/worker.rs:97
                        at util/src/panics.rs:86
                        at ../src/libstd/panic.rs:284
                        at ../src/libstd/panicking.rs:272
  12:       0x2b360fa14b - __rust_try
  13:       0x2b360fa0ee - __rust_maybe_catch_panic
  14:       0x2b35ac8787 - _<F as std..boxed..FnBox<A>>::call_box::h99f32fe7f22df6f9
                        at ../src/libstd/thread/local.rs:211
                        at ../src/libstd/panicking.rs:235
                        at ../src/libstd/panic.rs:387
                        at ../src/liballoc/boxed.rs:543
  15:       0x2b360ee574 - std::sys::thread::Thread::new::thread_start::h9e5bde00f3b3e2e2
  16:      0x29ad4a047cb - start_thread
  17:      0x29ad54429ec - clone
  18:                0x0 - <unknown>
2016-08-09 22:14:02 UTCINFO:parity::run: Finishing work, please wait...
```

> The machine has a raid setup and pretty slow io, but it's also running 3 geth instances and bitcoind. All of them had no io problems. Maybe parity is less forgiving for slow io?
It would be preferable when it would slow down instead of crashing though.

**Comment by gavofyork** [comment]
closing until we hear of secondary confirmations.
