### ISSUE TITLE
IPC connection failed while data-dir is configured on external hard disk

### ISSUE THREAD

**Issue by NikVolf** [ethcore/parity#1978]
originally reported by @markrtgh on gitter

```
thread 'IO Worker #1' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Custom(Custom { kind: TimedOut, error: StringError("Operation timed out") }) })', ../src/libcore/result.rs:788
stack backtrace:
   1:        0x10257bbf9 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:        0x102582570 - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:        0x102581330 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:        0x1025819b6 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:        0x102581854 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:        0x102581762 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:        0x1025816c7 - rust_begin_unwind
   8:        0x1025aee70 - core::panicking::panic_fmt::hc5789f4e80194729
   9:        0x101be2689 - core::result::unwrap_failed::h89892ccdb9882727
  10:        0x101c312af - _<ethsync..api..SyncClient<S> as ethsync..api..SyncProvider>::status::h63a9ace14025f034
  11:        0x101c55a1c - parity::informant::Informant::tick::h5bbd1c3e708c844e
  12:        0x101e8cb3a - std::panicking::try::do_call::heb5d59261a987a88
  13:        0x102582b5a - __rust_maybe_catch_panic
  14:        0x101f01c73 - _<F as alloc..boxed..FnBox<A>>::call_box::hc418f08edc31c253
  15:        0x102580915 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  16:     0x7fff842b299c - _pthread_body
  17:     0x7fff842b2919 - _pthread_start
thread 'IO Worker #2' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:788
stack backtrace:
2016-08-22 21:24:59 Finishing work, please wait...
   1:        0x10257bbf9 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:        0x102582570 - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:        0x102581330 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:        0x1025819b6 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:        0x102581854 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:        0x102581762 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:        0x1025816c7 - rust_begin_unwind
   8:        0x1025aee70 - core::panicking::panic_fmt::hc5789f4e80194729
   9:        0x101be22e8 - core::result::unwrap_failed::h66ea7893d7ca7f54
  10:        0x101c3104b - _<ethsync..api..SyncClient<S> as ethsync..api..SyncProvider>::status::h63a9ace14025f034
  11:        0x101c55a1c - parity::informant::Informant::tick::h5bbd1c3e708c844e
  12:        0x101e8cb3a - std::panicking::try::do_call::heb5d59261a987a88
  13:        0x102582b5a - __rust_maybe_catch_panic
  14:        0x101f01c73 - _<F as alloc..boxed..FnBox<A>>::call_box::hc418f08edc31c253
  15:        0x102580915 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  16:     0x7fff842b299c - _pthread_body
  17:     0x7fff842b2919 - _pthread_start
thread 'IO Worker #0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:788
stack backtrace:
   1:        0x10257bbf9 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:        0x102582570 - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:        0x102581330 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:        0x1025819b6 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:        0x102581854 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:        0x102581762 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:        0x1025816c7 - rust_begin_unwind
   8:        0x1025aee70 - core::panicking::panic_fmt::hc5789f4e80194729
   9:        0x101be22e8 - core::result::unwrap_failed::h66ea7893d7ca7f54
  10:        0x101c3104b - _<ethsync..api..SyncClient<S> as ethsync..api..SyncProvider>::status::h63a9ace14025f034
  11:        0x101c55a1c - parity::informant::Informant::tick::h5bbd1c3e708c844e
  12:        0x101e8cb3a - std::panicking::try::do_call::heb5d59261a987a88
  13:        0x102582b5a - __rust_maybe_catch_panic
  14:        0x101f01c73 - _<F as alloc..boxed..FnBox<A>>::call_box::hc418f08edc31c253
  15:        0x102580915 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  16:     0x7fff842b299c - _pthread_body
  17:     0x7fff842b2919 - _pthread_start
```

**Comment by gavofyork** [comment]
closing for now with #1983 in; @markrtgh please reopen if seen again
