### ISSUE TITLE
Parity crashes at some blocks when running with --pruning archive 

### ISSUE THREAD

**Issue by jo-tud** [ethcore/parity#2475]
Doing a sync with
`parity --tracing on --mode active --pruning archive`
Currently crashes parity on block 2371684.

Can be resumed, but I'm not sure if the db is still consistent.

```
...
2016-10-05 13:01:53 UTC Syncing #2371630 8fc3…d02e      1 blk/s   25 tx/s   1 Mgas/s       0+ 7957 Qed   #2379640    0/25/25 peers      2 KiB db    6 MiB chain   57 MiB queue   12 MiB sync

thread 'IO Worker #1' panicked at 'Traces database is incomplete.', ../src/libcore/option.rs:700
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-10-05 13:01:59 UTC Finishing work, please wait...
2016-10-05 13:01:59 UTC Stage 3 block verification failed for #2371684 (b58f…9b1a)
Error: Block(UnknownParent(0880fcfc8a501cc8c7dfd000d50fb1eb02a4f9ec65363bc73c7babb677cf1c12))
```
Parity
  version Parity/v1.4.0-unstable-48bb890-20161003/x86_64-linux-gnu/rustc1.12.0

**Comment by jo-tud** [comment]
Also happens for block 2358478

2016-10-05 12:30:39 UTC Syncing #2358431 88b3…6fee      6 blk/s   32 tx/s   5 Mgas/s       0+ 7273 Qed   #2365750    0/24/25 peers      2 KiB db    6 MiB chain   50 MiB queue   21 MiB sync
thread 'IO Worker #0' panicked at 'Traces database is incomplete.', ../src/libcore/option.rs:700
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-10-05 12:30:39 UTC Stage 3 block verification failed for #2358478 (6559…4564)
Error: Block(UnknownParent(64f1ae1b6aca1dbaedb3a094365477e0a64b3a1e75fbf75e01852ff9f892988c))
2016-10-05 12:30:39 UTC Finishing work, please wait...

**Comment by rphmeier** [comment]
Your trace database seems to have become corrupted; you may need to re-sync.

**Comment by keorn** [comment]
@jesuscript has set up a sync to see if we can reproduce it.
