### ISSUE TITLE
Running Parity twice crashes with weird random errors

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#2477]
Imho it should gently tell you that another instance is running, and the first instance should not crash.
Some stacks:
Instance 2:

```
$ ./target/release/parity 
Loading config file from /home/tomusdrw/.parity/config.toml
Migrating database from version 9 to 10
...............................................................................................................................................................................................................Migration finished
2016-10-05 20:01:37  main INFO parity::run  Starting Parity/v1.4.0-unstable-eae2466-20161005/x86_64-linux-gnu/rustc1.12.0
2016-10-05 20:01:37  main INFO parity::run  State DB configuation: fast
2016-10-05 20:01:37  main INFO ethcore::service  Configured for Morden using Ethash engine
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HandshakeFailed', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x55e5347a17e9 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x55e5347aa24c - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x55e5347a9119 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x55e5347a9808 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x55e5347a9662 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x55e5347a95d0 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x55e5347a9551 - rust_begin_unwind
   8:     0x55e5347e6c2f - core::panicking::panic_fmt::hbfc935564d134c1b
   9:     0x55e533c9e9d7 - core::result::unwrap_failed::h6edb3a5b672d6a2f
  10:     0x55e533dfc511 - parity::sync::main::hef7166b477bf0177
  11:     0x55e533e0bbd1 - parity::main::heae7138329c83e53
  12:     0x55e5347b1d36 - __rust_maybe_catch_panic
  13:     0x55e5347a8892 - std::rt::lang_start::h53bf99b0829cc03c
  14:     0x7f0292a32f44 - __libc_start_main
  15:     0x55e533b98fad - <unknown>
  16:                0x0 - <unknown>
```

Instance previously running (different version):

```
thread '<unnamed>' panicked at 'destination and source slices have different lengths', ../src/libcore/slice.rs:494
stack backtrace:
   1:     0x55d7b136878f - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x55d7b136f6eb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x55d7b136f36f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x55d7b1352ebe - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x55d7b136f931 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x55d7b1353b6a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x55d7b136f8ce - rust_begin_unwind
   8:     0x55d7b13a5def - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x55d7b13a60c8 - core::panicking::panic::heeca72c448510af4
  10:     0x55d7b11089eb - _<collections..string..String as ethcore_ipc..binary..BinaryConvertable>::to_bytes::h5f82220fef87e8c2
  11:     0x55d7b0d09d0e - _<collections..btree..map..BTreeMap<K, V> as ethcore_ipc..binary..BinaryConvertable>::to_bytes::h31a320584fcd7289
  12:     0x55d7b0d296da - _<ethcore..client..traits..BlockChainClient $u2b$$u20$$u27$static$u20$as$u20$ethcore_ipc..interface..IpcInterface$GT$::dispatch_buf::h3e216038588d8f9e
  13:     0x55d7b0df368d - std::panicking::try::call::ha1dcec043a30e98a
  14:     0x55d7b1376f4b - __rust_try
  15:     0x55d7b1376eee - __rust_maybe_catch_panic
  16:     0x55d7b0df437a - _<F as alloc..boxed..FnBox<A>>::call_box::h04ad564b165f9f79
  17:     0x55d7b136ddd4 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  18:     0x7f1b05387183 - start_thread
  19:     0x7f1b05db137c - clone
  20:                0x0 - <unknown>
thread 'IO Worker #3' panicked at 'index 8 out of range for slice of length 0', ../src/libcore/slice.rs:549
stack backtrace:
   1:     0x559368e0e78f - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x559368e156eb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x559368e1536f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x559368df8ebe - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x559368e15931 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x559368df9b6a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x559368e158ce - rust_begin_unwind
   8:     0x559368e4bdef - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x559368e4c063 - core::slice::slice_index_len_fail::ha4faf37254d75f20
  10:     0x55936838c84f - _<ethcore..client..traits..RemoteClient<S> as ethcore..client..traits..BlockChainClient>::chain_info::h8ea9df9988e24182
  11:     0x5593686ba5fb - ethsync::chain::ChainSync::on_packet::h2b28ef472eb320e7
  12:     0x5593686b0a29 - ethsync::chain::ChainSync::dispatch_packet::hf8c5a13c5a1fa6cd
  13:     0x5593686cbaa9 - _<ethsync..api..SyncProtocolHandler as ethcore_network..NetworkProtocolHandler>::read::h52f29de46bb1951f
  14:     0x559368b218e1 - _<ethcore_network..host..Host as ethcore_io..IoHandler<ethcore_network..host..NetworkIoMessage>>::stream_readable::ha6f45aaec2d709fb
  15:     0x559368b43024 - std::panicking::try::call::h8d4565c2eec3e678
  16:     0x559368e1cf4b - __rust_try
  17:     0x559368e1ceee - __rust_maybe_catch_panic
  18:     0x559368b446fc - _<F as alloc..boxed..FnBox<A>>::call_box::h625aab7db54ae2c4
  19:     0x559368e13dd4 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  20:     0x7f08a262c183 - start_thread
  21:     0x7f08a305637c - clone
  22:                0x0 - <unknown>
thread 'IO Worker #1' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x559368e0e78f - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x559368e156eb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x559368e1536f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x559368df8ebe - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x559368e15931 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x559368df9b6a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x559368e158ce - rust_begin_unwind
   8:     0x559368e4bdef - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x5593683605a0 - core::result::unwrap_failed::h4bfda949b9013638
  10:     0x55936838b896 - _<ethcore..client..traits..RemoteClient<S> as ethcore..client..traits..BlockChainClient>::queue_info::hfea974a4371d5f4f
  11:     0x5593686b635b - ethsync::chain::ChainSync::on_packet::h2b28ef472eb320e7
  12:     0x5593686b0a29 - ethsync::chain::ChainSync::dispatch_packet::hf8c5a13c5a1fa6cd
  13:     0x5593686cbaa9 - _<ethsync..api..SyncProtocolHandler as ethcore_network..NetworkProtocolHandler>::read::h52f29de46bb1951f
  14:     0x559368b218e1 - _<ethcore_network..host..Host as ethcore_io..IoHandler<ethcore_network..host..NetworkIoMessage>>::stream_readable::ha6f45aaec2d709fb
  15:     0x559368b43024 - std::panicking::try::call::h8d4565c2eec3e678
  16:     0x559368e1cf4b - __rust_try
  17:     0x559368e1ceee - __rust_maybe_catch_panic
  18:     0x559368b446fc - _<F as alloc..boxed..FnBox<A>>::call_box::h625aab7db54ae2c4
  19:     0x559368e13dd4 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  20:     0x7f08a262c183 - start_thread
  21:     0x7f08a305637c - clone
  22:                0x0 - <unknown>
thread 'IO Worker #0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x559368e0e78f - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x559368e156eb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x559368e1536f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x559368df8ebe - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x559368e15931 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x559368df9b6a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x559368e158ce - rust_begin_unwind
   8:     0x559368e4bdef - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x5593683605a0 - core::result::unwrap_failed::h4bfda949b9013638
  10:     0x55936839ecf0 - _<ethcore..client..traits..RemoteClient<S> as ethcore..client..traits..BlockChainClient>::pending_transactions::h552c6fedd4d99395
  11:     0x5593686c2476 - ethsync::chain::ChainSync::propagate_new_transactions::h19539e7a8dd9c499
  12:     0x5593686ccac2 - _<ethsync..api..SyncProtocolHandler as ethcore_network..NetworkProtocolHandler>::timeout::h9f03aa145033d20a
  13:     0x559368b287c7 - _<ethcore_network..host..Host as ethcore_io..IoHandler<ethcore_network..host..NetworkIoMessage>>::timeout::hb5c909ef5d615e2c
  14:     0x559368b430ba - std::panicking::try::call::h8d4565c2eec3e678
  15:     0x559368e1cf4b - __rust_try
  16:     0x559368e1ceee - __rust_maybe_catch_panic
  17:     0x559368b446fc - _<F as alloc..boxed..FnBox<A>>::call_box::h625aab7db54ae2c4
  18:     0x559368e13dd4 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  19:     0x7f08a262c183 - start_thread
  20:     0x7f08a305637c - clone
  21:                0x0 - <unknown>
thread 'IO Worker #2' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x559368e0e78f - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x559368e156eb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x559368e1536f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x559368df8ebe - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x559368e15931 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x559368df9b6a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x559368e158ce - rust_begin_unwind
   8:     0x559368e4bdef - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x5593683605a0 - core::result::unwrap_failed::h4bfda949b9013638
  10:     0x559368370246 - _<ethcore..client..traits..RemoteClient<S> as ethcore..client..traits..BlockChainClient>::block_status::h0ddbebc5c7aa25f7
  11:     0x5593686b5741 - ethsync::chain::ChainSync::on_packet::h2b28ef472eb320e7
  12:     0x5593686b0a29 - ethsync::chain::ChainSync::dispatch_packet::hf8c5a13c5a1fa6cd
  13:     0x5593686cbaa9 - _<ethsync..api..SyncProtocolHandler as ethcore_network..NetworkProtocolHandler>::read::h52f29de46bb1951f
  14:     0x559368b218e1 - _<ethcore_network..host..Host as ethcore_io..IoHandler<ethcore_network..host..NetworkIoMessage>>::stream_readable::ha6f45aaec2d709fb
  15:     0x559368b43024 - std::panicking::try::call::h8d4565c2eec3e678
  16:     0x559368e1cf4b - __rust_try
  17:     0x559368e1ceee - __rust_maybe_catch_panic
  18:     0x559368b446fc - _<F as alloc..boxed..FnBox<A>>::call_box::h625aab7db54ae2c4
  19:     0x559368e13dd4 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  20:     0x7f08a262c183 - start_thread
  21:     0x7f08a305637c - clone
  22:                0x0 - <unknown>
```

**Comment by NikVolf** [comment]
Should not be an issue with the disabled IPC
I have a nano transport update which will hopefully resolve it for 1.5

**Comment by gavofyork** [comment]
IPC issue - i'll shelve until we push forward with IPC.
