### ISSUE TITLE
Incomplete traces DB on master

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#2613]
```
2016-10-13 18:01:07 UTC Reorg to #2433933 6b72…b169 (d0fa…8693 #2433931 7845…76ab 02bd…c5fc)
thread 'IO Worker #3' panicked at 'Traces database is incomplete.', ../src/libcore/option.rs:700
stack backtrace:
1: 0x7fdc6a80b5c9 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
2: 0x7fdc6a81402c - std::panicking::defaulthook::{{closure}}::h7b8a142818383fb8
3: 0x7fdc6a812ef9 - std::panicking::default_hook::h41cf296f654245d7
4: 0x7fdc6a8135e8 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
5: 0x7fdc6a813442 - std::panicking::begin_panic::h93672d0313d5e8e9
6: 0x7fdc6a8133b0 - std::panicking::begin_panic_fmt::hd0daa02942245d81
7: 0x7fdc6a813331 - rust_begin_unwind
8: 0x7fdc6a850a0f - core::panicking::panic_fmt::hbfc935564d134c1b
9: 0x7fdc6a850a85 - core::option::expectfailed::h1d846c7a667396f7
10: 0x7fdc6a258f66 - <core..iter..Map<I, F> as core..iter..iterator..Iterator>::next::h49fafc0f98140016
11: 0x7fdc6a2f9c78 - _<ethcore..trace..db..TraceDB<T> as ethcore..trace..Database>::import::h9a1c1cecbad8f482
12: 0x7fdc6a28f988 - ethcore::client::client::Client::import_verifiedblocks::h8262d9a77082f565
13: 0x7fdc6a2f7294 - <ethcore..service..ClientIoHandler as ethcore_io..IoHandler<ethcore..service..ClientIoMessage>>::message::hea6e1d8c1fd57c6d
14: 0x7fdc6a15aecd - std::panicking::try::do_call::h8b819788124df3ca
15: 0x7fdc6a81bb16 - __rust_maybe_catchpanic
16: 0x7fdc6a18927e - <F as alloc..boxed..FnBox<A>>::call_box::h4bdaffb01162b4da
17: 0x7fdc6a811b92 - std::sys::thread::Thread::new::thread_start::h4c0ad33b336bc6ea
18: 0x7fdc68c07183 - start_thread
19: 0x7fdc6962337c - clone
20: 0x0 - <unknown>
2016-10-13 18:01:07 UTC Stage 3 block verification failed for #2433934 (1c08…8408)
Error: Block(UnknownParent(6b72055ba447fcd99d4cf073681cb3848291821a90f498c3a827549f536eb169))
2016-10-13 18:01:07 UTC Finishing work, please wait...
```

Reported on Gitter, Parity version:
`version Parity/v1.4.0-unstable-4bcc9e3-20161012/x86_64-linux-gnu/rustc1.12.0`

Initial sync done on older 1.4.0 version from master

**Comment by mtbitcoin** [comment]
Issue appears to be related to the reorgs.

**Comment by gavofyork** [comment]
another trace:

```
2016-10-15 16:34:36 UTC Imported #2445799 f859…c2f0 (0 txs, 0.00 Mgas, 1.22 ms, 0.51 KiB) + another 1 block(s)
2016-10-15 16:34:43 UTC Imported #2445800 cfe7…2af2 (9 txs, 0.46 Mgas, 341.70 ms, 2.26 KiB)
2016-10-15 16:34:55 UTC Reorg to #2445801 1790…a574 (cfe7…2af2 #2445799 f859…c2f0 1308…8024)
thread 'IO Worker #0' panicked at 'Traces database is incomplete.', ../src/libcore/option.rs:700
stack backtrace:
1: 0x7fbf94df7279 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
2: 0x7fbf94dffcdc - std::panicking::defaulthook::{{closure}}::h7b8a142818383fb8
3: 0x7fbf94dfeba9 - std::panicking::default_hook::h41cf296f654245d7
4: 0x7fbf94dff298 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
5: 0x7fbf94dff0f2 - std::panicking::begin_panic::h93672d0313d5e8e9
6: 0x7fbf94dff060 - std::panicking::begin_panic_fmt::hd0daa02942245d81
7: 0x7fbf94dfefe1 - rust_begin_unwind
8: 0x7fbf94e3c6bf - core::panicking::panic_fmt::hbfc935564d134c1b
9: 0x7fbf94e3c735 - core::option::expectfailed::h1d846c7a667396f7
10: 0x7fbf94842776 - <core..iter..Map<I, F> as core..iter..iterator..Iterator>::next::h49fafc0f98140016
11: 0x7fbf948e3be8 - _<ethcore..trace..db..TraceDB<T> as ethcore..trace..Database>::import::h9a1c1cecbad8f482
12: 0x7fbf9487972d - ethcore::client::client::Client::import_verifiedblocks::h8262d9a77082f565
13: 0x7fbf948e1204 - <ethcore..service..ClientIoHandler as ethcore_io..IoHandler<ethcore..service..ClientIoMessage>>::message::hea6e1d8c1fd57c6d
14: 0x7fbf94745f6d - std::panicking::try::do_call::h8b819788124df3ca
15: 0x7fbf94e077c6 - __rust_maybe_catchpanic
16: 0x7fbf9477432e - <F as alloc..boxed..FnBox<A>>::call_box::h4bdaffb01162b4da
17: 0x7fbf94dfd842 - std::sys::thread::Thread::new::thread_start::h4c0ad33b336bc6ea
18: 0x7fbf931e6183 - start_thread
19: 0x7fbf93c0237c - clone
20: 0x0 - <unknown>
2016-10-15 16:34:55 UTC Finishing work, please wait...
```

@debris?

**Comment by mtbitcoin** [comment]
2016-10-15 12:05:57  Reorg to #2403899 e1f9…c882 (0c64…267d #2403897 7256…ffb1 5e9c…bc7e)
thread 'IO Worker #2' panicked at 'Traces database is incomplete.', ../src/libcore\option.rs:700
stack backtrace:
   0:     0x7ff701a34c4e - <unknown>
   1:     0x7ff701a32b43 - <unknown>
   2:     0x7ff701a3360d - <unknown>
   3:     0x7ff701a33456 - <unknown>
   4:     0x7ff701a333b4 - <unknown>
   5:     0x7ff701a3334b - <unknown>
   6:     0x7ff701a40c15 - <unknown>
   7:     0x7ff701a40c85 - <unknown>
   8:     0x7ff701627a82 - <unknown>
   9:     0x7ff70169b1a1 - <unknown>
  10:     0x7ff701667fa8 - <unknown>
  11:     0x7ff701504272 - <unknown>
  12:     0x7ff701a36e11 - <unknown>
  13:     0x7ff701535755 - <unknown>
  14:     0x7ff701a3097e - <unknown>
  15:     0x7ffae13d8363 - BaseThreadInitThunk
2016-10-15 12:05:57  Stage 3 block verification failed for #2403952 (a24b…73e6)
Error: Block(UnknownParent(ecc220db10573e8e0b7be52c07497e2ef810462764fe6a325d68114145f994fa))
2016-10-15 12:05:57  Finishing work, please wait...

**Comment by mtbitcoin** [comment]
At the moment, this issue prevents running the fork ready master client node with tracing. May i know if the issue will be fixed before the fork?

**Comment by gavofyork** [comment]
we'll do our best; we're treating it as high priority.

**Comment by gavofyork** [comment]
@mtbitcoin could i just check which version you are running?

**Comment by mtbitcoin** [comment]
the latest master release 
Starting Parity/v1.4.0-unstable-b5c65e3-20161016/x86_64-windows-msvc/rustc1.12.0

If it helps its the issue occurred only after the '20161008' release, so it must have been something introduced between then and now

**Comment by mtbitcoin** [comment]
I don't mean to sound pushy, but may I know if this has a chance to make it through before the hard fork? Switching between beta and master requires a resync
