### ISSUE TITLE
Parity crash with new token input

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2615]
1. Ran signer-dapps branch
2. Entered new UI via localhost:8180 (should have been 127.0.0.1:8180, but was running with no validation)
3. Signer asked for a token, opened a new terminal to generate the token via `parity signer new-token`
4. Pasted the token into the UI to authorize
5. Boom, crash, bang. Panic.

Repeated the process (this time corrected the IP and didn't use --signer-no-validation), same process, parity in one console, new token gen in another console. No issues this time.

Trace -

```
parity git:(signer-dapps) ✗ parity --testnet --signer-no-validation                                                                   
2016-10-13 21:32:46  Starting Parity/v1.4.0-unstable-52184d1-20161008/x86_64-macos/rustc1.13.0-nightly
2016-10-13 21:32:46  State DB configuation: fast
2016-10-13 21:32:46  Configured for Morden using Ethash engine
2016-10-13 21:32:49  Error starting network: StdIo(Error { repr: Os { code: 48, message: "Address already in use" } })
2016-10-13 21:32:49  *** INSECURE *** Running Trusted Signer with no origin validation.
2016-10-13 21:32:49  If you do not intend this, exit now.
2016-10-13 21:33:04  Unauthorized connection to Signer API blocked.
2016-10-13 21:33:04  Unauthorized connection to Signer API blocked.
2016-10-13 21:33:20      0/ 0/25 peers     38 MiB db    9 KiB chain    2 KiB queue    4 KiB sync
thread '<unnamed>' panicked at 'index 8 out of range for slice of length 0', ../src/libcore/slice.rs:541
stack backtrace:
   1:        0x101d3185a - std::sys::backtrace::tracing::imp::write::h46f28e67d38b4637
   2:        0x101d37faf - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
   3:        0x101d36f45 - std::panicking::default_hook::h96c288d728df3ebf
   4:        0x101d37556 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   5:        0x101d373f4 - std::panicking::begin_panic::hfbeda5aad583dc32
   6:        0x101d37312 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   7:        0x101d37277 - rust_begin_unwind
   8:        0x101d64fb0 - core::panicking::panic_fmt::h4395919ece15c671
   9:        0x101d65089 - core::slice::slice_index_len_fail::h98d51f66eb16cf45
  10:        0x1012ca0a7 - <ethsync::api::SyncClient<S> as ethsync::api::SyncProvider>::peers::h18fe6f308f181ae4
  11:        0x1011d6179 - <ethcore_rpc::v1::impls::ethcore::EthcoreClient<C, M, S, F> as ethcore_rpc::v1::traits::ethcore::Ethcore>::net_peers::h9147267d7fb750ba
  12:        0x10113ecaa - <jsonrpc_core::io::DelegateMethod<T, F> as jsonrpc_core::commander::MethodCommand>::execute::h23109e85346faae1
  13:        0x101952873 - jsonrpc_core::commander::Commander::execute_method::h3100ccf2508813a0
  14:        0x10195381f - jsonrpc_core::request_handler::RequestHandler::handle_call::hdcd49871006d1ba6
  15:        0x101952de5 - jsonrpc_core::request_handler::RequestHandler::handle_request::h333a29d613d549fb
  16:        0x1019559c2 - jsonrpc_core::io::IoHandler::handle_request::hc303efea7ca8b4e9
  17:        0x1014d8875 - <ethcore_signer::ws_server::session::Session as ws::handler::Handler>::on_message::hf9767a879291b32a
  18:        0x1014ba515 - <ws::connection::Connection<H>>::read_frames::h0ffae6f7eda23554
  19:        0x1014bf85e - <ws::connection::Connection<H>>::read::h5004bf0b7123e1fb
  20:        0x1014ccfe4 - <ws::io::Handler<F> as mio::handler::Handler>::ready::h8fbb2eabd7f38c6a
  21:        0x1014adbd9 - <ws::WebSocket<F>>::listen::h23525b1067e53597
  22:        0x1014b4328 - std::panicking::try::do_call::h6c6f07fb1e9a38ef
  23:        0x101d3856a - __rust_maybe_catch_panic
  24:        0x1014cbeda - <F as alloc::boxed::FnBox<A>>::call_box::h28b57e69ac944815
  25:        0x101d365f4 - std::sys::thread::Thread::new::thread_start::h5b631f48cd23f128
  26:     0x7fff9523099c - _pthread_body
  27:     0x7fff95230919 - _pthread_start
2016-10-13 21:33:29  Finishing work, please wait...
2016-10-13 21:33:29  Signer: Broadcaster was not closed cleanly. Details: WS Error <Queue(NotifyError::Closed(..))>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:783
stack backtrace:
   1:        0x101d3185a - std::sys::backtrace::tracing::imp::write::h46f28e67d38b4637
   2:        0x101d37faf - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
   3:        0x101d36f45 - std::panicking::default_hook::h96c288d728df3ebf
   4:        0x101d37556 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   5:        0x101d373f4 - std::panicking::begin_panic::hfbeda5aad583dc32
   6:        0x101d37312 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   7:        0x101d37277 - rust_begin_unwind
   8:        0x101d64fb0 - core::panicking::panic_fmt::h4395919ece15c671
   9:        0x1014c94f1 - core::result::unwrap_failed::h826d1e65f62f2c7c
  10:        0x1014de83f - <ethcore_signer::ws_server::Server as core::ops::Drop>::drop::hd7e84ec8c87f02fc
  11:        0x101335c44 - parity::run::execute::hf0bf4c81acdd02d0
  12:        0x1013489ef - parity::execute::h826e353d6b929bca
  13:        0x101354e39 - parity::main::h1cb0abae157587a9
  14:        0x101d3856a - __rust_maybe_catch_panic
  15:        0x101d36a86 - std::rt::lang_start::haaae1186de9de8cb
➜  parity git:(signer-dapps) ✗
```

@tomusdrw As discussed.

**Comment by tomusdrw** [comment]
Perhaps IPC is initialized during signer token generation which basically could lead to errors like with Parity started twice #2477

**Comment by tomusdrw** [comment]
I've checked the code and IPC is not initialized when just creating a token. The issue is related to IPC, which is now disabled.
That said, I think what may caused the issue:
1. Accidentaly running second instance of Parity (token generation is probably un-related, it's just that RPC triggered IPC call that caused the crash)
2. Removing `~/.parity/ipc` directory

I think this should be re-opened if the problem happens again in future when IPC is enabled back.
