### ISSUE TITLE
Parity.js relying on global `fetch`

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#3471]
```
const Api = require('@parity/parity.js').Api;
const transport = new Api.Transport.Http('http://localhost:8545');
const api = new Api(transport);

api.eth
  .coinbase()
  .then((coinbase) => {
    console.log('The coinbase is', coinbase);
  });

=======================================================

/home/kyroy/node_modules/@parity/parity.js/library.js:3
[...]

ReferenceError: fetch is not defined
    at e.value (/home/kyroy/node_modules/@parity/parity.js/library.js:3:15183)
    at e.r._pollConnection (/home/kyroy/node_modules/@parity/parity.js/library.js:3:14669)
    at new e (/home/kyroy/node_modules/@parity/parity.js/library.js:3:14760)
    at Object.<anonymous> (/home/kyroy/github/offchain-computation-verification/contracts/mm_single_client_parity.js:2:17)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
```

Should probably use some kind of https://github.com/matthew-andrews/isomorphic-fetch instead.

**Comment by jacogr** [comment]
Definitely an issue, the build should bring in these dependencies into the WebPack bundle.
