### ISSUE TITLE
Trace_filter crash when using `fromBlock: "earliest"`

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#3571]
Originally reported in #3567

fromBlock: 'earliest' + fromAccount for example '0x6c637709f5ba4c1cdf758fb46b30ea4940db5d44' (only 1 tx on ropsten so far) crashes parity with:

```
2016-11-22 14:31:59  Imported #20479 911d…446c (0 txs, 0.00 Mgas, 0.99 ms, 0.52 KiB)
thread '<unnamed>' panicked at 'Expected to find a trace. Db is probably corrupted.', ../src/libcore/option.rs:705
stack backtrace:
   1:     0x7f8de41b702f - <unknown>
   2:     0x7f8de41bee2d - <unknown>
   3:     0x7f8de41bd78a - <unknown>
   4:     0x7f8de41bdd88 - <unknown>
   5:     0x7f8de41bdc22 - <unknown>
   6:     0x7f8de41bdb60 - <unknown>
   7:     0x7f8de41bdae1 - <unknown>
   8:     0x7f8de41fa10f - <unknown>
   9:     0x7f8de41fa185 - <unknown>
  10:     0x7f8de3d20472 - <unknown>
  11:     0x7f8de3d50373 - <unknown>
  12:     0x7f8de37bf098 - <unknown>
  13:     0x7f8de377ab18 - <unknown>
  14:     0x7f8de3b1a787 - <unknown>
  15:     0x7f8de3b1b904 - <unknown>
  16:     0x7f8de3b1adc3 - <unknown>
  17:     0x7f8de3b1d943 - <unknown>
  18:     0x7f8de3afce90 - <unknown>
  19:     0x7f8de3af5bfd - <unknown>
  20:     0x7f8de3af5d68 - <unknown>
  21:     0x7f8de3af5ada - <unknown>
  22:     0x7f8de3af3de3 - <unknown>
  23:     0x7f8de3af21b5 - <unknown>
  24:     0x7f8de3ae6a2d - <unknown>
  25:     0x7f8de3aef57f - <unknown>
  26:     0x7f8de3ae62e7 - <unknown>
  27:     0x7f8de41c68f6 - <unknown>
  28:     0x7f8de3aefc54 - <unknown>
  29:     0x7f8de41bc560 - <unknown>
  30:     0x7f8de27690a3 - start_thread
  31:     0x7f8de317962c - clone
  32:                0x0 - <unknown>
2016-11-22 14:31:59  Finishing work, please wait...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Closed', ../src/libcore/result.rs:799
stack backtrace:
   1:     0x7f8de41b702f - <unknown>
   2:     0x7f8de41bee2d - <unknown>
   3:     0x7f8de41bd78a - <unknown>
   4:     0x7f8de41bdd88 - <unknown>
   5:     0x7f8de41bdc22 - <unknown>
   6:     0x7f8de41bdb60 - <unknown>
   7:     0x7f8de41bdae1 - <unknown>
   8:     0x7f8de41fa10f - <unknown>
   9:     0x7f8de4141a75 - <unknown>
  10:     0x7f8de4155fa9 - <unknown>
  11:     0x7f8de3b05249 - <unknown>
  12:     0x7f8de3829fef - <unknown>
  13:     0x7f8de3909c2c - <unknown>
  14:     0x7f8de3912453 - <unknown>
  15:     0x7f8de391ef7d - <unknown>
  16:     0x7f8de41c68f6 - <unknown>
  17:     0x7f8de41bd001 - <unknown>
  18:     0x7f8de30b2b44 - __libc_start_main
  19:     0x7f8de376382d - <unknown>
  20:                0x0 - <unknown>
```

**Comment by SinErgy84** [comment]
if it helps you:
fromBlock: 'earliest' -> crash
fromBlock: 1 -> no crash, correct result

**Comment by tomusdrw** [comment]
Very helpful, thank you. Probably we expect traces for genesis block to be present and it's not there.
