### ISSUE TITLE
web3.personal.unlockAccount method not found

### ISSUE THREAD

**Issue by aordine** [ethcore/parity#3575]
Getting this after parity upgrade:
```
> var Web3 = require('web3');
undefined                                                                                                                                   
> var web3 = new Web3();
undefined                                                                                                                                   
> web3.setProvider(new Web3.providers.HttpProvider('http://localhost:8545'));
undefined                                                                                                                                   
> web3.personal.unlockAccount(web3.eth.accounts[0],"I go 0 to a 100 real quick",1000);
Error: Method not found                                                                                                                     
    at Object.module.exports.InvalidResponse (/root/node_modules/web3/lib/web3/errors.js:35:16)                                             
    at RequestManager.send (/root/node_modules/web3/lib/web3/requestmanager.js:61:22)                                                       
    at Personal.send [as unlockAccount] (/root/node_modules/web3/lib/web3/method.js:145:58)                                                 
    at repl:1:15                                                                                                                            
    at REPLServer.defaultEval (repl.js:248:27)                                                                                              
    at bound (domain.js:280:14)                                                                                                             
    at REPLServer.runBound [as eval] (domain.js:293:12)                                                                                     
    at REPLServer.<anonymous> (repl.js:412:12)                                                                                              
    at emitOne (events.js:82:20)                                                                                                            
    at REPLServer.emit (events.js:169:7)                                                                                                    
> 
> web3.eth.blockNumber
2675509
```

**Comment by tomusdrw** [comment]
`personal` namespace is no longer exposed by default due to security reasons, please run with `--jsonrpc-apis web3,eth,net,parity,traces,rpc,personal`

**Comment by williambanks** [comment]
Could info like this possibly be included somewhere?  Like at the top of the RPC section?  I wasted 8 hours trying to track down why a script I wrote to interface with parity, directly following the docs on the site was erroring out.  Did a site search, couldn't find anything.  Finally went to closed issues and found this.  It's literally the only info I can even find on the subject.

In my use case I'm using this as the ETH wallet for a crypto exchange and parity is sitting isolated on the VPN, so there could have been hundreds of reasons it didn't work.  After a day of searching, it turns out it's just outdated docs. It's been almost 5 months since this issue was closed, but there doesn't seem to be a peep about it anywhere unless I'm missing something vital.  In which case please point me there.

Thanks!

**Comment by tomusdrw** [comment]
Hi!
We're now including breaking changes in release notes (have a look at 1.5.0: https://github.com/ethcore/parity/releases/tag/v1.5.0).

RPC apis exposed by default are also displayed in `parity --help` in relative RPC section.

Could you point us to docs that were updated?

You can also always reach us on Parity Gitter channel: http://gitter.im/ethcore/parity to get instant support.
