### ISSUE TITLE
Can't sync: verifier panicked

### ISSUE THREAD

**Issue by cemsbr** [ethcore/parity#3634]
With only _keys_ folder below _~/.parity_, I ran `parity ui` and got the error below. Running `parity` again gives the same "panicked" error immediately. Version is `Parity/v1.4.5-beta-a028d04-20161126/x86_64-linux-gnu/rustc1.13.0`.

```
2016-11-27 13:59:42  Syncing  #560357 dc0f…a3a5    300 blk/s  404 tx/s  11 Mgas/s   25189+    0 Qed    #585548    0/25/25 peers
     13 MiB db    9 MiB chain   53 MiB queue    7 MiB sync
thread 'Verifier #1' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', ../src/libcore/result.rs:799
stack backtrace:
thread 'Verifier #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', ../src/libcore/result.rs:799
   1:     0x561b08d9f0ff - <unknown>
   2:     0x561b08da6efd - <unknown>
   3:     0x561b08da585a - <unknown>
   4:     0x561b08da5e58 - <unknown>
   5:     0x561b08da5cf2 - <unknown>
   6:     0x561b08da5c30 - <unknown>
   7:     0x561b08da5bb1 - <unknown>
   8:     0x561b08de21df - <unknown>
   9:     0x561b08833f58 - <unknown>
  10:     0x561b08926746 - <unknown>
  11:     0x561b0881051f - <unknown>
  12:     0x561b08dae9c6 - <unknown>
  13:     0x561b088459dc - <unknown>
  14:     0x561b08da4630 - <unknown>
  15:     0x7f0121b36453 - start_thread
  16:     0x7f01225c47de - __GI___clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x561b08d9f0ff - <unknown>
   2:     0x561b08da6efd - <unknown>
   3:     0x561b08da585a - <unknown>
   4:     0x561b08da5e58 - <unknown>
   5:     0x561b08da5cf2 - <unknown>
   6:     0x561b08da5c30 - <unknown>
   7:     0x561b08da5bb1 - <unknown>
   8:     0x561b08de21df - <unknown>
   9:     0x561b08833f58 - <unknown>
  10:     0x561b08926746 - <unknown>
  11:     0x561b0881051f - <unknown>
2016-11-27 13:59:51  Finishing work, please wait...
12:     0x561b08dae9c6 - <unknown>
  13:     0x561b088459dc - <unknown>
  14:     0x561b08da4630 - <unknown>
  15:     0x7f0121b36453 - start_thread
  16:     0x7f01225c47de - __GI___clone
  17:                0x0 - <unknown>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:799
stack backtrace:
   1:     0x561b08d9f0ff - <unknown>
   2:     0x561b08da6efd - <unknown>
   3:     0x561b08da585a - <unknown>
   4:     0x561b08da5e58 - <unknown>
   5:     0x561b08da5cf2 - <unknown>
   6:     0x561b08da5c30 - <unknown>
   7:     0x561b08da5bb1 - <unknown>
   8:     0x561b08de21df - <unknown>
   9:     0x561b08833e90 - <unknown>
  10:     0x561b08837249 - <unknown>
  11:     0x561b08836c68 - <unknown>
  12:     0x561b083ecd02 - <unknown>
  13:     0x561b083ed0be - <unknown>
  14:     0x561b0840a428 - <unknown>
  15:     0x561b084f12d1 - <unknown>
  16:     0x561b084f9733 - <unknown>
  17:     0x561b0850625d - <unknown>
  18:     0x561b08dae9c6 - <unknown>
  19:     0x561b08da50d1 - <unknown>
  20:     0x7f01224fc290 - __libc_start_main
  21:     0x561b0834aaad - <unknown>
  22:                0x0 - <unknown>
```

**Comment by o0ragman0o** [comment]
same.
Ubuntu 14.04

results of ` parity -l sync=trace 2> errlog.txt` are attached.
[errlog.txt](https://github.com/ethcore/parity/files/616366/errlog.txt)

**Comment by arkpar** [comment]
See #3432
