### ISSUE TITLE
Panic from `unwrap`

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3638]
```
thread 'IO Worker #3' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } }', ../src/libcore/result.rs:799
stack backtrace:
   1:        0x1064d1518 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x1064d76af - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x1064d60b5 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x1064d66c6 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x1064d6564 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x1064d6482 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x1064d63e7 - rust_begin_unwind
   8:        0x106502fe0 - core::panicking::panic_fmt::h27224b181f9f037f
   9:        0x1060fded0 - core::result::unwrap_failed::hbbe45964de00535c
  10:        0x1061015fc - https_fetch::client::Client::with_limit::h328adc4cf0dc3e6f
  11:        0x1060f6866 - <fetch::client::Client as core::default::Default>::default::hffe67dc8fda4a16a
  12:        0x1060c9bf6 - ethcore_hash_fetch::client::Client::new::h2af29e359221ff6c
  13:        0x105f6a79d - ethcore::client::updater::Updater::tick::h64b30118318b208a
  14:        0x105f4fcb0 - ethcore::client::client::Client::tick::hf618bd561c7c1682
  15:        0x105f76809 - <ethcore::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::service::ClientIoMessage>>::timeout::h1e0b40fd5b4c481f
  16:        0x105e13573 - std::panicking::try::do_call::h54ced78f7373a7c6
  17:        0x1064d7c6a - __rust_maybe_catch_panic
  18:        0x105e48a84 - <F as alloc::boxed::FnBox<A>>::call_box::he9f1f2a3bd457a20
  19:        0x1064d5764 - std::sys::thread::Thread::new::thread_start::h759e10bc4abc7e72
  20:     0x7fff81b3a99c - _pthread_body
  21:     0x7fff81b3a919 - _pthread_start
```

**Comment by gavofyork** [comment]
happened again:

```
thread 'IO Worker #2' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } }', ../src/libcore/result.rs:799
stack backtrace:
   1:        0x10ac46518 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x10ac4c6af - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x10ac4b0b5 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x10ac4b6c6 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x10ac4b564 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x10ac4b482 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x10ac4b3e7 - rust_begin_unwind
   8:        0x10ac77fe0 - core::panicking::panic_fmt::h27224b181f9f037f
   9:        0x10a872ed0 - core::result::unwrap_failed::hbbe45964de00535c
  10:        0x10a8765fc - https_fetch::client::Client::with_limit::h328adc4cf0dc3e6f
  11:        0x10a86b866 - <fetch::client::Client as core::default::Default>::default::hffe67dc8fda4a16a
  12:        0x10a83ebf6 - ethcore_hash_fetch::client::Client::new::h2af29e359221ff6c
  13:        0x10a6df79d - ethcore::client::updater::Updater::tick::h64b30118318b208a
  14:        0x10a6c4cb0 - ethcore::client::client::Client::tick::hf618bd561c7c1682
  15:        0x10a6eb809 - <ethcore::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::service::ClientIoMessage>>::timeout::h1e0b40fd5b4c481f
  16:        0x10a588573 - std::panicking::try::do_call::h54ced78f7373a7c6
  17:        0x10ac4cc6a - __rust_maybe_catch_panic
  18:        0x10a5bda84 - <F as alloc::boxed::FnBox<A>>::call_box::he9f1f2a3bd457a20
  19:        0x10ac4a764 - std::sys::thread::Thread::new::thread_start::h759e10bc4abc7e72
  20:     0x7fff81b3a99c - _pthread_body
  21:     0x7fff81b3a919 - _pthread_start
```

**Comment by tomusdrw** [comment]
Does it still occur when `FetchClient` is re-used?

**Comment by gavofyork** [comment]
apparently not.
