### ISSUE TITLE
Building master fails

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3737]
I report this issue since I have usually no problem building master.

I am at 1f0a02b638ebb53077fc08a4a13bd0558ce1e37a

The issue seem to occur in webpack during  a full build done with:
`cargo build --release --no-default-features --features ui`

```
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "run" "build:app"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! parity.js@0.2.96 build:app: `webpack --config webpack/app --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the parity.js@0.2.96 build:app script 'webpack --config webpack/app --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parity.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack/app --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parity.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parity.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../ethereum/parity/js/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! parity.js@0.2.96 build: `npm run build:lib && npm run build:dll && npm run build:app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parity.js@0.2.96 build script 'npm run build:lib && npm run build:dll && npm run build:app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parity.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:lib && npm run build:dll && npm run build:app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parity.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parity.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../ethereum/parity/js/npm-debug.log
thread 'main' panicked at 'There was an error build JS code.', /Users/.../ethereum/parity/target/release/build/parity-dapps-glue-841c953adb3ca8f8/out/lib.rs:471
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jacogr** [comment]
@ngotchac  Any ideas? I'm on fresh master, no issues (just ran though)

**Comment by chevdor** [comment]
The issue remains here after a `cargo clean`.

**Comment by chevdor** [comment]
I tested on a second machine where I do *NOT* get the issue. It still is annoying but if this is a single machine, I invite you to reduce your efforts on this one and I will dig further what the issue can be.

**Comment by jacogr** [comment]
Could you try `rm -rf js/node_modules/`?

**Comment by chevdor** [comment]
I tried, it did not help. I may have add sync issues in the parity folder so I will clone again.

**Comment by ngotchac** [comment]
You might want to pas the content of `/Users/.../ethereum/parity/js/npm-debug.log` here (if anyà

**Comment by chevdor** [comment]
Same issue after clone from scratch.
@ngotchac here it is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle parity.js@0.2.97~prebuild: parity.js@0.2.97
6 silly lifecycle parity.js@0.2.97~prebuild: no script for prebuild, continuing
7 info lifecycle parity.js@0.2.97~build: parity.js@0.2.97
8 verbose lifecycle parity.js@0.2.97~build: unsafe-perm in lifecycle true
9 verbose lifecycle parity.js@0.2.97~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/will/projects/parity/js/node_modules/.bin:/usr/local/Cellar/node/7.2.0/bin:/Users/will/.cargo/bin:/Users/will/.rvm/gems/ruby-2.3.0/bin:/Users/will/.rvm/gems/ruby-2.3.0@global/bin:/Users/will/.rvm/rubies/ruby-2.3.0/bin:/usr/local/heroku/bin:/Users/will/go//bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/bin:/usr/local/share/npm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/bin:/usr/local/texlive/2013/bin/universal-darwin:/Users/will/bin:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin:/Users/will/.rvm/bin:/Users/will/.rvm/bin:/Users/will/.cargo/bin:/Users/will/.multirust/toolchains/stable-x86_64-apple-darwin/bin
10 verbose lifecycle parity.js@0.2.97~build: CWD: /Users/will/projects/parity/js
11 silly lifecycle parity.js@0.2.97~build: Args: [ '-c',
11 silly lifecycle   'npm run build:lib && npm run build:dll && npm run build:app' ]
12 silly lifecycle parity.js@0.2.97~build: Returned: code: 1  signal: null
13 info lifecycle parity.js@0.2.97~build: Failed to exec build script
14 verbose stack Error: parity.js@0.2.97 build: `npm run build:lib && npm run build:dll && npm run build:app`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid parity.js@0.2.97
16 verbose cwd /Users/will/projects/parity/js
17 error Darwin 16.1.0
18 error argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v7.2.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error parity.js@0.2.97 build: `npm run build:lib && npm run build:dll && npm run build:app`
22 error Exit status 1
23 error Failed at the parity.js@0.2.97 build script 'npm run build:lib && npm run build:dll && npm run build:app'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the parity.js package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:lib && npm run build:dll && npm run build:app
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs parity.js
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls parity.js
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ngotchac** [comment]
Hmmm... It doesn't say much... What if you execute `cd js && npm run build` ?

**Comment by chevdor** [comment]
and indeed, running `npm run build:lib && npm run build:dll && npm run build:app` from the js folder fails at the end in the optimization steps.

I have webpack 1.13.2 installed globally.
I updated to 1.14.0 with no success.

**Comment by chevdor** [comment]
The relevant error seems to be
````
ERROR in ./views/Signer/components/TransactionPendingForm/TransactionPendingForm.js
Module not found: Error: Can't resolve './TransactionPendingForm.css' in '/Users/will/projects/parity/js/src/views/Signer/components/TransactionPendingForm'
 @ ./views/Signer/components/TransactionPendingForm/TransactionPendingForm.js 23:0-50
 @ ./views/Signer/components/TransactionPendingForm/index.js
 @ ./views/Signer/components/SignRequest/SignRequest.js
 @ ./views/Signer/components/SignRequest/index.js
 @ ./views/Signer/components/RequestPending/requestPending.js
 @ ./views/Signer/components/RequestPending/index.js
 @ ./views/Signer/containers/Embedded/embedded.js
 @ ./views/Signer/containers/Embedded/index.js
 @ ./views/Signer/index.js
 @ ./views/index.js
 @ ./main.js
 @ ./index.js
````

**Comment by chevdor** [comment]
OK, the issue is only on my side.

It came from the fact that I sync this folder and the sync software, surely to help me, renamed a file with a `_conflict`.

**Comment by jacogr** [comment]
Thanks for the update. Logs were definitely not much use here :(
