### ISSUE TITLE
Crash when syncing chain with 1.5.0 unstable (tracing, archive pruning and fat-db ON)

### ISSUE THREAD

**Issue by jo-tud** [ethcore/parity#4048]
Parity command: `parity --tracing on --pruning archive --fat-db on --scale-verifiers -d /home/myuser/io.parity.ethereum`

Version: `Parity/v1.5.0-unstable-4c532f9-20170104/x86_64-linux-gnu/rustc1.14.0`

```
...
2017-01-04 15:58:49 UTC Syncing #1242912 74d2…2fcd    335 blk/s 1981 tx/s  69 Mgas/s   15877+    0 Qed   #1258791    2/25/25 peers     16 MiB db    5 MiB chain   56 MiB queue   10 MiB sync
thread 'Verifier #0' panicked at 'assertion failed: rc == -1', util/src/journaldb/archivedb.rs:138
stack backtrace:
   1:     0x5624235e613a - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5624235efaef - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x5624235ed816 - std::panicking::default_hook::h5897799da33ece67
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x5624235edec7 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x5624233a7faf - std::panicking::begin_panic::h634e2b37a96f78d4
   6:     0x5624233bc47b - <ethcore_util::journaldb::archivedb::ArchiveDB as ethcore_util::journaldb::traits::JournalDB>::journal_under::h0d22308071c630a3
   7:     0x5624232089b0 - ethcore::state_db::StateDB::journal_under::h37a4c356b02ef549
   8:     0x562423148e91 - ethcore::client::client::Client::import_verified_blocks::h41831aa7a9d97032
   9:     0x562423067c52 - <ethcore_io::service::IoChannel<Message>>::send_sync::h1e721fd1660e8fb9
  10:     0x5624231ddd2f - ethcore::verification::queue::QueueSignal::set_sync::h1d1dee079263f592
  11:     0x562422fc5e05 - std::panicking::try::do_call::hc0900f322d953640
  12:     0x5624235f712b - <unknown>
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libpanic_abort/lib.rs:40
Aborted (core dumped)
```

This reproduced at a second run with same config.

**Comment by rphmeier** [comment]
This seems very suspect. Will take a look into it.

**Comment by rphmeier** [comment]
Out of curiosity, does the problem persist when _not_ running with `--fat-db on`?

**Comment by jo-tud** [comment]
Syncing just went past the problematic block range without `--fat-db`

**Comment by rphmeier** [comment]
Ok, I've reproduced this. 

The main issue is that somehow, a storage key or account is getting removed from the trie twice.
This leads to an assertion failure in archivedb. I think a similar (and simpler) failure could occur if an account or storage key were modified twice within the same block.

The simple workaround is to have FatDB check whether the key already exists in the trie before storing/removing its preimage from the database.

The larger problem at hand is the fact that double-removal is happening at all -- it really shouldn't be possible.

**Comment by rphmeier** [comment]
@jo-tud Hi, I've prepared a fix which works locally. Could you test it as well?

**Comment by jo-tud** [comment]
Yes, of course

**Comment by rphmeier** [comment]
As for the origin of the double-removal, I think what's happening is this:
```
TX1:
  Remove storage X. storage_at(X) != empty, so set storage_changes(X) to remove.
  commit, calling storage_trie.remove(X)
  aux_key(X) rc == -1

TX2:
  Set storage X to Y. storage_at(X) != Y, so set storage_changes(X) to Y
  Remove storage X. storage_at(X) != empty, so set storage_changes(X) to remove
  commit, calling storage_trie.remove(X)
  aux_key(X) rc == -2
```

@arkpar A possible solution could be to have `Account::set_storage` just remove the `storage_changes` entry if it's equal to the cached entry rather than overwrite?

**Comment by jo-tud** [comment]
Crash doesn't occur with 705daef
