### ISSUE TITLE
Panic on sync with "Missing key counter"

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#412]
Second time I've seen this. not easily reproducible.

```
[ 0 d4e5…b1cb8fa3 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 3/3 peers, 0 downloaded, 0+0 queued ···//  2264 (0) bl  3712 (0) ex ]
[ 197 56f4…edb4a497 ]---[ 39 blk/s | 0 tx/s | 0 gas/s  //··· 3/3 peers, 197 downloaded, 0+0 queued ···//  166904 (164640) bl  36096 (32384) ex ]
[ 781 2fd6…2b00b8af ]---[ 117 blk/s | 0 tx/s | 0 gas/s  //··· 3/3 peers, 960 downloaded, 76+3 queued ···//  59176 (-107728) bl  127392 (91296) ex ]
thread 'IO Worker #3' panicked at 'Missing key counter', ../src/libcore/option.rs:704
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'IO Worker #3' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:746
```

note: seems to happen when it gets to block #1000. second run gives:

```
root@bench:~# parity 
INFO:ethcore_util::network::service: Host ID=2fbd95a7823c0a36405f53382d184a5c4cd30a969e24207b921142bbed7ea80eccb40f71bef215d677e01e616e3e66edf92d961657d989cbc83133ceee12a1be
INFO:ethcore::service: Starting Parity/0.9.0/x86_64-gnu-linux
INFO:ethcore::service: Configured for Frontier using Ethash engine
INFO:ethsync::chain: Connected 51:Geth/v1.3.3-c541b38f/linux/go1.5.1
INFO:ethsync::chain: Connected 50:Geth/v1.3.3-c541b38f/linux/go1.5.1
INFO:ethsync::chain: Connected 49:Geth/v1.3.3-c541b38f/linux/go1.5.1
[ 1000 5b45…6a7b5d58 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 3/3 peers, 0 downloaded, 0+0 queued ···//  2264 (0) bl  3712 (0) ex ]
[ 1000 5b45…6a7b5d58 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 2/3 peers, 1000 downloaded, 0+0 queued ···//  2264 (0) bl  3712 (0) ex ]
INFO:ethsync::chain: Disconnected 51:unknown
[ 1000 5b45…6a7b5d58 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 1/2 peers, 1000 downloaded, 0+0 queued ···//  2264 (0) bl  3712 (0) ex ]
INFO:ethsync::chain: Connected 51:Geth/v1.3.3-c541b38f/linux/go1.5.1
[ 1000 5b45…6a7b5d58 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 2/3 peers, 1000 downloaded, 0+0 queued ···//  2264 (0) bl  3712 (0) ex ]
TrieDB::new(97fb…00e17be5): Trie root not found!
thread 'IO Worker #3' panicked at 'Trie root not found!', util/src/trie/triedb.rs:64
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'IO Worker #3' panicked at 'called `Result::unwrap()` on an `Err` value: AnyWARN:ethcore::client: Stage 3 block verification failed for #1004 (3aa1…360f89c2)
Error: Block(UnknownParent(8b83375cdc6a3490595b1cde985a810bea9bdb6df601c4f07719629a59ab520d))
', ../src/libcore/result.rs:746
```

**Comment by arkpar** [comment]
JournalDB end era marker is not committed to the DB during first 1000 blocks

**Comment by gavofyork** [comment]
so if you ctrl-c during that time it'll break?

**Comment by arkpar** [comment]
yes
