### ISSUE TITLE
Panic during sync with 'new peer already exists'

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#419]
two nodes, same machine, one was syncing from the other.

```
[ 623897 aff1…689b91cc ]---[ 555 blk/s | 728 tx/s | 24113626 gas/s  //··· 0/1 peers, 658919 downloaded, 0+34981 queued ···//  2936000 (267776) bl  1050240 (8512) ex ]
[ 625961 2d9e…6a18315e ]---[ 412 blk/s | 612 tx/s | 23015200 gas/s  //··· 0/1 peers, 658919 downloaded, 0+32933 queued ···//  2575680 (-360320) bl  1027488 (-22752) ex ]
INFO:ethsync::chain: Disconnected 48:unknown
INFO:ethsync::chain: Connected 48:Parity/0.9.0/x86_64-gnu-linux
thread 'IO Worker #1' panicked at 'ChainSync: new peer already exists', sync/src/chain.rs:299
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'IO Worker #1' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:746
```

**Comment by gavofyork** [comment]
it's possible this is already fixed; was actually running a pre-#416 build.
