### ISSUE TITLE
Invalid character 'U' at position 1'

### ISSUE THREAD

**Issue by tensor5** [ethcore/parity#4225]
I just finished compiling Parity v1.5.0 on Arch Linux with `cargo build --release`, and I get the following error when I try to run it:

```
2017-01-19 18:39:52  Starting Parity/v1.5.0-unstable-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.14.0
2017-01-19 18:39:52  State DB configuration: fast
2017-01-19 18:39:52  Operating mode: active
2017-01-19 18:39:52  Configured for Frontier/Homestead using Ethash engine
2017-01-19 18:39:52  Updated conversion rate to Ξ1 = US$10.39 (11457903000 wei/gas)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid character 'U' at position 1', src/libcore/result.rs:837
stack backtrace:
   1:     0x5573053c2f9a - <unknown>
   2:     0x5573053cc95f - <unknown>
   3:     0x5573053ca67c - <unknown>
   4:     0x5573053cad37 - <unknown>
   5:     0x5573053cabc4 - <unknown>
   6:     0x5573053caae9 - <unknown>
   7:     0x5573053caa77 - <unknown>
   8:     0x55730540e97d - <unknown>
   9:     0x557305175736 - <unknown>
  10:     0x557305176d02 - <unknown>
  11:     0x557304c758c9 - <unknown>
  12:     0x557304c563a8 - <unknown>
  13:     0x557304a6ac37 - <unknown>
  14:     0x557304a76ac3 - <unknown>
  15:     0x557304a7e10b - <unknown>
  16:     0x557304a80b7d - <unknown>
  17:     0x5573053d3e2b - <unknown>
Aborted (core dumped)
```

Any help? Thanks.

**Comment by arkpar** [comment]
Could you try `cargo build` without `--release`? This should produce a more detailed trace dump.

**Comment by tensor5** [comment]
```
2017-01-19 19:42:04  Starting Parity/v1.5.0-unstable-UNKNOWN-UNKNOWN/x86_64-linux-gnu/rustc1.14.0
2017-01-19 19:42:04  State DB configuration: fast
2017-01-19 19:42:04  Operating mode: active
2017-01-19 19:42:04  Configured for Frontier/Homestead using Ethash engine
2017-01-19 19:42:05  Updated conversion rate to Ξ1 = US$10.4 (11446886000 wei/gas)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid character 'U' at position 1', src/libcore/result.rs:837
stack backtrace:
   1:     0x55c9a1f8448a - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /build/rust/src/rustc-1.14.0/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55c9a1f8de4f - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:247
   3:     0x55c9a1f8bb6c - std::panicking::default_hook::h5897799da33ece67
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:263
   4:     0x55c9a1f8c227 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:451
   5:     0x55c9a1f8c0b4 - std::panicking::begin_panic::hbb38be1379e09df0
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:413
   6:     0x55c9a1f8bfd9 - std::panicking::begin_panic_fmt::h26713cea9bce3ab0
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:397
   7:     0x55c9a1f8bf67 - rust_begin_unwind
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:373
   8:     0x55c9a1fd03fd - core::panicking::panic_fmt::hcfbb59eeb7f27f75
                        at /build/rust/src/rustc-1.14.0/src/libcore/panicking.rs:69
   9:     0x55c9a19ee495 - core::result::unwrap_failed::h054b0face10c4638
                        at /build/rust/src/rustc-1.14.0/src/libcore/macros.rs:29
  10:     0x55c9a19ecbb9 - <core::result::Result<T, E>>::unwrap::he0f25f1ef471ba0c
                        at /build/rust/src/rustc-1.14.0/src/libcore/result.rs:737
  11:     0x55c9a19f39bc - <ethcore_bigint::hash::H160 as core::convert::From<&'static str>>::from::he5b31c8bd626c1e5
                        at /build/parity/src/parity-1.5.0/util/bigint/src/hash.rs:453
  12:     0x55c9a0575a3a - <T as core::convert::Into<U>>::into::h2d2213956ce1c97f
                        at /build/rust/src/rustc-1.14.0/src/libcore/convert.rs:271
  13:     0x55c9a0576c47 - ipc_common_types::types::version_info::VersionInfo::this::h8b8e3684db3a2061
                        at /build/parity/src/parity-1.5.0/ipc-common-types/src/types/mod.rs:20
  14:     0x55c9a04e4bb1 - parity_updater::updater::Updater::new::hd745615f9b17a0dd
                        at /build/parity/src/parity-1.5.0/updater/src/updater.rs:126
  15:     0x55c99fdfa0ed - parity::run::execute::hb473744a9df6b067
                        at /build/parity/src/parity-1.5.0/parity/run.rs:344
  16:     0x55c99fe049ec - parity::execute::h8079808622f9aa2d
                        at /build/parity/src/parity-1.5.0/parity/main.rs:153
  17:     0x55c99fe062cd - parity::start::hc083e74d1176efc3
                        at /build/parity/src/parity-1.5.0/parity/main.rs:179
  18:     0x55c99fe06971 - parity::main_direct::he044134c1d7a81a7
                        at /build/parity/src/parity-1.5.0/parity/main.rs:248
  19:     0x55c99fe07c06 - parity::main::h8a2dfbe8258e52ae
                        at /build/parity/src/parity-1.5.0/parity/main.rs:299
  20:     0x55c9a1f957ba - __rust_maybe_catch_panic
                        at /build/rust/src/rustc-1.14.0/src/libpanic_unwind/lib.rs:97
  21:     0x55c9a1f8cc45 - std::rt::lang_start::hd661476ce2fc2931
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:332
                        at /build/rust/src/rustc-1.14.0/src/libstd/panic.rs:351
                        at /build/rust/src/rustc-1.14.0/src/libstd/rt.rs:57
  22:     0x55c99ff337f2 - main
  23:     0x7f2a7841c290 - __libc_start_main
  24:     0x55c99f5c7299 - _start
  25:                0x0 - <unknown>
```

**Comment by arkpar** [comment]
Looks like this happens when building outside of the git repo. Build from a repository as a workaround until a fix is available.

**Comment by tensor5** [comment]
Thanks!
