### ISSUE TITLE
Event subscription tests has random failures

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#4274]
e.g. Running tests -

```
 1615 passing (13s)
  6 pending
  1 failing

  1) util/subscribe-to-events checks for new events regularly:
     AssertionError: expected 0 to be at least 1
      at Context._callee5$ (src/util/subscribe-to-events.spec.js:113:38)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:355:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at run (node_modules/core-js/library/modules/es6.promise.js:87:22)
      at node_modules/core-js/library/modules/es6.promise.js:100:28
      at flush (node_modules/core-js/library/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

Re-running the tests -

```
1616 passing (13s)
  6 pending
```

**Comment by jacogr** [comment]
More today & last night -

```
 1617 passing (17s)
  6 pending
  1 failing

  1) util/subscribe-to-events checks for new events regularly:
     AssertionError: expected 0 to be at least 1
      at Context._callee5$ (src/util/subscribe-to-events.spec.js:113:38)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:355:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at run (node_modules/core-js/library/modules/es6.promise.js:87:22)
      at node_modules/core-js/library/modules/es6.promise.js:100:28
      at flush (node_modules/core-js/library/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```
