### ISSUE TITLE
Tendermint test hangs or fails spouriously

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#4333]
```
---- engines::tendermint::tests::relays_messages stdout ----
	thread 'engines::tendermint::tests::relays_messages' panicked at 'called `Result::unwrap()` on an `Err` value: Engine(DoubleVote(82a978b3f5962a5b0957d9ee9eef472ee55b42f1))', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
stack backtrace:
   1:     0x55efe730934c - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55efe730f22e - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55efe730edd3 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x55efe730f6cb - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55efe730f564 - std::panicking::begin_panic::hc4c5d184a1e3fb7c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x55efe730f489 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x55efe730f417 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x55efe733b83d - core::panicking::panic_fmt::h1016b85b51d1931f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55efe6236cc5 - core::result::unwrap_failed::h7e659fb26bca7692
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:29
  10:     0x55efe614b1c3 - <core::result::Result<T, E>>::unwrap::h1f3d27aaf27560c2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:745
  11:     0x55efe6768e0a - ethcore::engines::tendermint::tests::vote::h9cabf613b3b3884f
                        at /home/tomusdrw/eth/parity/ethcore/src/engines/tendermint/mod.rs:679
  12:     0x55efe676d3b0 - ethcore::engines::tendermint::tests::relays_messages::hbe0c6a9ebdfebaf5
                        at /home/tomusdrw/eth/parity/ethcore/src/engines/tendermint/mod.rs:876
  13:     0x55efe6a0851e - <F as test::FnBox<T>>::call_box::h0a98498b8201ff98
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libtest/lib.rs:1366
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libtest/lib.rs:140
  14:     0x55efe731673a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  15:     0x55efe69fca5a - std::panicking::try::do_call::h066c775502ca82e3
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libtest/lib.rs:1311
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
  16:     0x55efe731673a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  17:     0x55efe6a03686 - <F as alloc::boxed::FnBox<A>>::call_box::h5882ce3c9c178b6d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  18:     0x55efe730e524 - std::sys::imp::thread::Thread::new::thread_start::h76badbf9b0ecaf58
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  19:     0x7f8e6bd2c6b9 - start_thread
  20:     0x7f8e6b84b82c - clone
  21:                0x0 - <unknown>


failures:
    engines::tendermint::tests::relays_messages
```

or

```
test engines::tendermint::tests::relays_messages has been running for over 60 seconds
```

@keorn are you on this?

**Comment by keorn** [comment]
Is it your local machine? I dont see it on CI. Will have a look at that test.

**Comment by tomusdrw** [comment]
Yes, that happend locally for me, but there were also issues on CI regarding spurious build failures caused by timeouts.
