### ISSUE TITLE
Panic from out-of-bounds access

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#487]
```
[ #1039599 5bec…2d15 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 0/20 peers, #1039599, 0+0 queued ···//  17188568 (15520384) bl  59520 (0) ex ]
[ #1039599 5bec…2d15 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 0/20 peers, #1039599, 0+0 queued ···//  1668184 (-15520384) bl  59520 (0) ex ]
[ #1039599 5bec…2d15 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 0/21 peers, #1039599, 0+0 queued ···//  21704408 (20036224) bl  59520 (0) ex ]
[ #1039599 5bec…2d15 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 0/21 peers, #1039599, 0+0 queued ···//  20460760 (-1243648) bl  59520 (0) ex ]
[ #1039600 6286…29ea ]---[ 0 blk/s | 0 tx/s | 4200 gas/s  //··· 0/22 peers, #1039600, 0+0 queued ···//  24221912 (3761152) bl  67680 (8160) ex ]
[ #1039601 1ec7…47c0 ]---[ 0 blk/s | 0 tx/s | 8400 gas/s  //··· 0/23 peers, #1039601, 0+0 queued ···//  1668184 (-22553728) bl  59520 (-8160) ex ]
[ #1039601 1ec7…47c0 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 0/24 peers, #1039601, 0+0 queued ···//  22253528 (20585344) bl  59520 (0) ex ]
thread 'IO Worker #3' panicked at 'index out of bounds: the len is 0 but the index is 0', ../src/libcollections/vec.rs:1134
thread 'IO Worker #2' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:688
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:688
```

**Comment by arkpar** [comment]
```
thread 'IO Worker #0' panicked at 'index out of bounds: the len is 0 but the index is 0', ../src/libcollections/vec.rs:1134
stack backtrace:
   1:     0x7f9eab4a9130 - sys::backtrace::tracing::imp::write::hf7e21f48f7cb711bEju
   2:     0x7f9eab4ab7e5 - panicking::default_handler::_<closure>::closure.42503
   3:     0x7f9eab4ab28f - panicking::default_handler::hac4d0be12e3129d2Gwy
   4:     0x7f9eab497ed6 - sys_common::unwind::begin_unwind_inner::hf13a3e016c1e78e1bct
   5:     0x7f9eab498638 - sys_common::unwind::begin_unwind_fmt::h878e9fd8b85e0857hbt
   6:     0x7f9eab4a8771 - rust_begin_unwind
   7:     0x7f9eab4dd7af - panicking::panic_fmt::h9f005ee999496200zYL
   8:     0x7f9eab4dd922 - panicking::panic_bounds_check::h164576bc413dcf81FXL
   9:     0x7f9eab230fbc - network::session::Session::send_packet::h5af48445855fcf548du
                        at ../src/libcollections/vec.rs:1134
                        at util/src/network/session.rs:185
  10:     0x7f9eab10039d - network::host::NetworkContext<'s, Message>::send::h5029656454783030788
                        at util/src/network/host.rs:192
  11:     0x7f9eab0e5c2a - EthSync.NetworkProtocolHandler<SyncMessage>::connected::h61cad3f2aaa04c21B5c
                        at sync/src/io.rs:72
                        at sync/src/chain.rs:899
                        at sync/src/chain.rs:558
                        at sync/src/lib.rs:121
  12:     0x7f9eab1b8a04 - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::stream_readable::h4933979545082660577
                        at util/src/network/host.rs:628
                        at util/src/network/host.rs:777
  13:     0x7f9eab19d727 - sys_common::unwind::try::try_fn::h9165269918729648367
                        at util/src/io/worker.rs:103
                        at util/src/io/worker.rs:95
                        at util/src/io/worker.rs:70
                        at util/src/panics.rs:77
                        at util/src/io/worker.rs:69
                        at ../src/libstd/thread/mod.rs:277
                        at ../src/libstd/sys/common/unwind/mod.rs:153
  14:     0x7f9eab4a8708 - __rust_try
  15:     0x7f9eab4a4cfb - sys_common::unwind::try::inner_try::h7232ca0b9dac160cJ8s
  16:     0x7f9eab19f059 - boxed::F.FnBox<A>::call_box::h1949166278203384102
                        at ../src/libstd/sys/common/unwind/mod.rs:123
                        at ../src/libstd/thread/mod.rs:277
                        at ../src/liballoc/boxed.rs:541
  17:     0x7f9eab4aa203 - sys::thread::Thread::new::thread_start::h93f164b37c9b35e1Ctx
  18:     0x7f9ea9fad181 - start_thread
  19:     0x7f9eaa7c747c - __clone
  20:                0x0 - <unknown>
```
