### ISSUE TITLE
JournalDB throws away node under certain circumstances

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#568]
both both zero and one.parity.io miss a separate but the same node:
` Worker #3' panicked at 'Not found! 99560b90c5cd57230c18b87a474f675cbaba12af253f0f39a91650c098340633` at 1,086,998.

my local machine misses a different node. logs from my machine:

```
[ #1080620 e2dc…276f ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 4/6 peers, #1080620, 0+0 queued ···// mem: 6 KiB chain, 2 KiB queue, 233 KiB sync ]
thread 'IO Worker #3' panicked at 'Not found! e6e37323300c80cbdbc2da9b28b907dba362858dd3f3753d64d7d750db7b1f89', util/src/trie/triedb.rs:215
2016-03-02 11:09:56 WARN:client: Stage 3 block verification failed for #1081755 (aa1c…3ae6)
Error: Block(UnknownParent(9e2bf712869914b2ea634457e16e196c798d341927020c9a168735467075c707))
```

second run:

```
[ #1081709 1e07…0b7b ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 3/3 peers, #1081709, 0+0 queued ···// mem: 9 KiB chain, 2 KiB queue, 349 KiB sync ]
thread 'IO Worker #2' panicked at 'Not found! e6e37323300c80cbdbc2da9b28b907dba362858dd3f3753d64d7d750db7b1f89', util/src/trie/triedb.rs:215
2016-03-02 11:24:15 WARN:client: Stage 3 block verification failed for #1081713 (ef3d…4587)
Error: Block(UnknownParent(5bcde33c348afc2de8de52aaaf9ea8f9288d2d22c39258c5f641ffa3dcf5668c))
```

third run:

```
thread 'IO Worker #0' panicked at 'Not found! e6e37323300c80cbdbc2da9b28b907dba362858dd3f3753d64d7d750db7b1f89', util/src/trie/triedb.rs:215
2016-03-02 11:35:44 WARN:client: Stage 3 block verification failed for #1081760 (9235…f97e)
Error: Block(UnknownParent(ca99be14f91677912a0c5cdbc5aa7c14f6344fe73ca0b7a3d004f1f327fd7352))
```

fourth with backtrace:
```
thread 'IO Worker #0' panicked at 'Not found! e6e37323300c80cbdbc2da9b28b907dba362858dd3f3753d64d7d750db7b1f89', util/src/trie/triedb.rs:215
stack backtrace:
   1:     0x55968b3793c0 - sys::backtrace::tracing::imp::write::hf7e21f48f7cb711bEju
   2:     0x55968b37c155 - panicking::default_handler::_<closure>::closure.42503
   3:     0x55968b37bbff - panicking::default_handler::hac4d0be12e3129d2Gwy
   4:     0x55968b3620f6 - sys_common::unwind::begin_unwind_inner::hf13a3e016c1e78e1bct
   5:     0x55968b362858 - sys_common::unwind::begin_unwind_fmt::h878e9fd8b85e0857hbt
   6:     0x55968b0d7a97 - trie::triedb::TrieDB<'db>::get_raw_or_lookup::h7697f5f22c738ef0Vtl
   7:     0x55968b0d7c42 - trie::triedb::TrieDB<'db>::get_from_node::heef343e89f5481e1xsl
   8:     0x55968b0d7c7c - trie::triedb::TrieDB<'db>::get_from_node::heef343e89f5481e1xsl
   9:     0x55968b0d7c7c - trie::triedb::TrieDB<'db>::get_from_node::heef343e89f5481e1xsl
  10:     0x55968b0de90a - trie::sectriedb::SecTrieDB<'db>.Trie::get::hc0978f028b4aebb1p7m
  11:     0x55968b0922ac - state::State::get::hd1490f9a96204355h3h
  12:     0x55968b02be50 - state::State::code::h760fc30c3825ac5diUh
  13:     0x55968aff8915 - block::OpenBlock<'x>::push_transaction::h7c65a9032ed50fe8Doa
  14:     0x55968affe618 - block::enact::h02d30d171822a3a3Ewa
  15:     0x55968affebc0 - block::enact_verified::h3828d76c2d009e5f2Aa
  16:     0x55968b00e6d9 - client::Client::check_and_close_block::h45cb020d7882ea4chab
  17:     0x55968b013e9a - client::Client::import_verified_blocks::haac8ce155415a7bacjb
  18:     0x55968b06df47 - service::ClientIoHandler.IoHandler<NetSyncMessage>::message::h025b637fd64103bckpd
  19:     0x55968b04d830 - sys_common::unwind::try::try_fn::h3177092287983102021
  20:     0x55968b378998 - __rust_try
  21:     0x55968b3732ab - sys_common::unwind::try::inner_try::h7232ca0b9dac160cJ8s
  22:     0x55968b04ee90 - boxed::F.FnBox<A>::call_box::h5666765628413589348
  23:     0x55968b37ab73 - sys::thread::Thread::new::thread_start::h93f164b37c9b35e1Ctx
  24:     0x7f0bdee886a9 - start_thread
  25:     0x7f0be0065e9c - clone
  26:                0x0 - <unknown>
2016-03-02 11:36:36 WARN:client: Stage 3 block verification failed for #1081714 (6604…2284)
Error: Block(UnknownParent(ef3d1df75cbce2d094df485f9d9a0b9040b63fac1ea0d05a804105e1ac784587))
```

fifth:

```
[ #1081709 1e07…0b7b ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 3/4 peers, #1081709, 0+0 queued ···// mem: 9 KiB chain, 2 KiB queue, 714 KiB sync ]
2016-03-02 11:45:18 DEBUG:ethcore::client: Best: 1081709, importing: 1081710
thread 'IO Worker #3' panicked at 'Not found! e6e37323300c80cbdbc2da9b28b907dba362858dd3f3753d64d7d750db7b1f89', util/src/trie/triedb.rs:215
stack backtrace:
   1:     0x55ae433b8510 - sys::backtrace::tracing::imp::write::hf7e21f48f7cb711bEju
   2:     0x55ae433bb2a5 - panicking::default_handler::_<closure>::closure.42503
   3:     0x55ae433bad4f - panicking::default_handler::hac4d0be12e3129d2Gwy
   4:     0x55ae433a1246 - sys_common::unwind::begin_unwind_inner::hf13a3e016c1e78e1bct
   5:     0x55ae433a19a8 - sys_common::unwind::begin_unwind_fmt::h878e9fd8b85e0857hbt
   6:     0x55ae43116be7 - trie::triedb::TrieDB<'db>::get_raw_or_lookup::h7697f5f22c738ef0Vtl
   7:     0x55ae43116d92 - trie::triedb::TrieDB<'db>::get_from_node::heef343e89f5481e1xsl
   8:     0x55ae43116dcc - trie::triedb::TrieDB<'db>::get_from_node::heef343e89f5481e1xsl
   9:     0x55ae43116dcc - trie::triedb::TrieDB<'db>::get_from_node::heef343e89f5481e1xsl
  10:     0x55ae4311da5a - trie::sectriedb::SecTrieDB<'db>.Trie::get::hc0978f028b4aebb1p7m
  11:     0x55ae430d13fc - state::State::get::h572dc814ac054c5an4h
  12:     0x55ae4306afa0 - state::State::code::h2ea2b01b5b2aac03oVh
  13:     0x55ae43037975 - block::OpenBlock<'x>::push_transaction::h6bb4ae7311e7b857Doa
  14:     0x55ae4303d678 - block::enact::h7f21804ecd7cd4fdEwa
  15:     0x55ae4303dc20 - block::enact_verified::h152c27b2b4f7e2302Aa
  16:     0x55ae4304d829 - client::Client::check_and_close_block::h439bc7567cb88791hab
  17:     0x55ae43052fea - client::Client::import_verified_blocks::h8d0b609d84ecc225ikb
  18:     0x55ae430ad097 - service::ClientIoHandler.IoHandler<NetSyncMessage>::message::h5eff195f511abe53qqd
  19:     0x55ae4308c980 - sys_common::unwind::try::try_fn::h10112821256078123487
  20:     0x55ae433b7ae8 - __rust_try
  21:     0x55ae433b23fb - sys_common::unwind::try::inner_try::h7232ca0b9dac160cJ8s
  22:     0x55ae4308dfe0 - boxed::F.FnBox<A>::call_box::h10614111530638818600
  23:     0x55ae433b9cc3 - sys::thread::Thread::new::thread_start::h93f164b37c9b35e1Ctx
  24:     0x7fb7907ab6a9 - start_thread
  25:     0x7fb791988e9c - clone
  26:                0x0 - <unknown>
2016-03-02 11:45:18 DEBUG:ethcore::client: Best: 1081709, importing: 1081713
2016-03-02 11:45:18 WARN:client: Stage 3 block verification failed for #1081713 (ef3d…4587)
Error: Block(UnknownParent(5bcde33c348afc2de8de52aaaf9ea8f9288d2d22c39258c5f641ffa3dcf5668c))
```

**Comment by gavofyork** [comment]
Fixed in #613
