### ISSUE TITLE
parity panicked during sync

### ISSUE THREAD

**Issue by debris** [ethcore/parity#623]
internet connection was really bad at the time. parity panicked and shutdown.

```
[ #993769 8e9e…4f28 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 1/3 peers, #993769, 0+0 queued ···// mem: 126 KiB chain, 2 KiB queue, 3 MiB sync ]
[ #993769 8e9e…4f28 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 5/5 peers, #993769, 0+0 queued ···// mem: 126 KiB chain, 2 KiB queue, 4 MiB sync ]
2016-03-07 09:49:06 Error sending packet: Network(Expired)
thread 'IO Worker #1' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
   1:        0x10d01ece8 - sys::backtrace::tracing::imp::write::h4c3934d94b73ae74jYu
   2:        0x10d022175 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43867
   3:        0x10d021d98 - panicking::default_handler::h31854fe07604bc37Ipz
   4:        0x10d00a3f6 - sys_common::unwind::begin_unwind_inner::hb0e3e92ad83708955Wt
   5:        0x10d00a8ae - sys_common::unwind::begin_unwind_fmt::ha54ff2e9794a0b31bWt
   6:        0x10d01e2a7 - rust_begin_unwind
   7:        0x10d0444a0 - panicking::panic_fmt::h71118c177c5714b4lcM
   8:        0x10d04479c - panicking::panic::h62d0499da58dfdf5SaM
   9:        0x10cbc619f - EthSync.NetworkProtocolHandler<SyncMessage>::message::h97e34c422354fbf1nzd
  10:        0x10cc2ced4 - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::message::h7103975100664505824
  11:        0x10cc1cc08 - sys_common::unwind::try::try_fn::h2620030356090436169
  12:        0x10d01e23b - __rust_try
  13:        0x10d019963 - sys_common::unwind::inner_try::ha4dd38239be80d4f7Tt
  14:        0x10cc1de8f - boxed::F.FnBox<A>::call_box::h6191962482758311089
  15:        0x10d02153c - sys::thread::Thread::new::thread_start::hbedb614b5a7b16469Dy
  16:     0x7fff91d749b0 - _pthread_body
  17:     0x7fff91d7492d - _pthread_start
thread 'IO Worker #0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10d01ece8 - sys::backtrace::tracing::imp::write::h4c3934d94b73ae74jYu
   2:        0x10d022175 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43867
   3:        0x10d021d98 - panicking::default_handler::h31854fe07604bc37Ipz
   4:        0x10d00a3f6 - sys_common::unwind::begin_unwind_inner::hb0e3e92ad83708955Wt
   5:        0x10d00a8ae - sys_common::unwind::begin_unwind_fmt::ha54ff2e9794a0b31bWt
   6:        0x10d01e2a7 - rust_begin_unwind
   7:        0x10d0444a0 - panicking::panic_fmt::h71118c177c5714b4lcM
   8:        0x10cbc75c9 - result::unwrap_failed::h4981893780761508013
   9:        0x10cbc51d1 - EthSync.NetworkProtocolHandler<SyncMessage>::disconnected::h90363a43be0ec2a8fyd
  10:        0x10cc25f4b - network::host::Host<Message>::kill_connection::h7183086428269586981
  11:        0x10cc2ee50 - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::stream_hup::h15647756746564488932
  12:        0x10cc1cca5 - sys_common::unwind::try::try_fn::h2620030356090436169
  13:        0x10d01e23b - __rust_try
  14:        0x10d019963 - sys_common::unwind::inner_try::ha4dd38239be80d4f7Tt
  15:        0x10cc1de8f - boxed::F.FnBox<A>::call_box::h6191962482758311089
  16:        0x10d02153c - sys::thread::Thread::new::thread_start::hbedb614b5a7b16469Dy
  17:     0x7fff91d749b0 - _pthread_body
  18:     0x7fff91d7492d - _pthread_start
thread 'IO Worker #2' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10d01ece8 - sys::backtrace::tracing::imp::write::h4c3934d94b73ae74jYu
   2:        0x10d022175 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43867
   3:        0x10d021d98 - panicking::default_handler::h31854fe07604bc37Ipz
   4:        0x10d00a3f6 - sys_common::unwind::begin_unwind_inner::hb0e3e92ad83708955Wt
   5:        0x10d00a8ae - sys_common::unwind::begin_unwind_fmt::ha54ff2e9794a0b31bWt
   6:        0x10d01e2a7 - rust_begin_unwind
   7:        0x10d0444a0 - panicking::panic_fmt::h71118c177c5714b4lcM
   8:        0x10cbc75c9 - result::unwrap_failed::h4981893780761508013
   9:        0x10cbc51d1 - EthSync.NetworkProtocolHandler<SyncMessage>::disconnected::h90363a43be0ec2a8fyd
  10:        0x10cc25f4b - network::host::Host<Message>::kill_connection::h7183086428269586981
  11:        0x10cc2ee50 - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::stream_hup::h15647756746564488932
  12:        0x10cc1cca5 - sys_common::unwind::try::try_fn::h2620030356090436169
  13:        0x10d01e23b - __rust_try
  14:        0x10d019963 - sys_common::unwind::inner_try::ha4dd38239be80d4f7Tt
  15:        0x10cc1de8f - boxed::F.FnBox<A>::call_box::h6191962482758311089
  16:        0x10d02153c - sys::thread::Thread::new::thread_start::hbedb614b5a7b16469Dy
  17:     0x7fff91d749b0 - _pthread_body
  18:     0x7fff91d7492d - _pthread_start
thread 'IO Worker #3' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x10d01ece8 - sys::backtrace::tracing::imp::write::h4c3934d94b73ae74jYu
   2:        0x10d022175 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43867
   3:        0x10d021d98 - panicking::default_handler::h31854fe07604bc37Ipz
   4:        0x10d00a3f6 - sys_common::unwind::begin_unwind_inner::hb0e3e92ad83708955Wt
   5:        0x10d00a8ae - sys_common::unwind::begin_unwind_fmt::ha54ff2e9794a0b31bWt
   6:        0x10d01e2a7 - rust_begin_unwind
   7:        0x10d0444a0 - panicking::panic_fmt::h71118c177c5714b4lcM
   8:        0x10cbc75c9 - result::unwrap_failed::h4981893780761508013
   9:        0x10cbc4aec - EthSync.NetworkProtocolHandler<SyncMessage>::read::h4cd34227602edef37wd
  10:        0x10cc32013 - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::stream_readable::h2061856584532379008
  11:        0x10cc1cb14 - sys_common::unwind::try::try_fn::h2620030356090436169
  12:        0x10d01e23b - __rust_try
  13:        0x10d019963 - sys_common::unwind::inner_try::ha4dd38239be80d4f7Tt
  14:        0x10cc1de8f - boxed::F.FnBox<A>::call_box::h6191962482758311089
  15:        0x10d02153c - sys::thread::Thread::new::thread_start::hbedb614b5a7b16469Dy
  16:     0x7fff91d749b0 - _pthread_body
  17:     0x7fff91d7492d - _pthread_start
```

**Comment by gavofyork** [comment]
me too
```
thread 'IO Worker #3' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
   1:     0x55c347a5dbd0 - sys::backtrace::tracing::imp::write::h1df2fc52f5a1077eehv
   2:     0x55c347a61deb - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44584
   3:     0x55c347a61a58 - panicking::default_handler::hdd51c136086dc3e0CWz
   4:     0x55c347a491dc - sys_common::unwind::begin_unwind_inner::h3a281a3586db30a7x5t
   5:     0x55c347a49668 - sys_common::unwind::begin_unwind_fmt::heafd13fa24ecdc24D4t
   6:     0x55c347a5d041 - rust_begin_unwind
   7:     0x55c347a9160f - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x55c347a918e8 - panicking::panic::h4265c0105caa1121SaM
   9:     0x55c347625a6e - EthSync.NetworkProtocolHandler<SyncMessage>::message::h287122d0adbd9438nzd
  10:     0x55c347688cee - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::message::h15254353766173586079
  11:     0x55c3476789f2 - sys_common::unwind::try::try_fn::h10698231780134667756
  12:     0x55c347a5cfcb - __rust_try
  13:     0x55c347a5857d - sys_common::unwind::inner_try::h6de88a54d8fb341cz2t
  14:     0x55c347679d30 - boxed::F.FnBox<A>::call_box::h5349811147428443626
  15:     0x55c347a60969 - sys::thread::Thread::new::thread_start::ha2764ce591c12364WTy
  16:     0x7fea3cf8d6a9 - start_thread
  17:     0x7fea3db38e9c - clone
  18:                0x0 - <unknown>
```
