### ISSUE TITLE
Another panic in network code

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#625]
```
thread 'IO Worker #0' panicked at 'Error updating discovery registration: Io(Mio(Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("Network IO notification error") }) }))', ../src/libcore/result.rs:thread 'IO Worker #1' panicked at 'Error updating discovery registration: Io(Mio(Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("Network IO notification error") }) }))', ../src/libcore/result.rs:746
stack backtrace:
746
thread 'IO Worker #3' panicked at 'Error updating discovery registration: Io(Mio(Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("Network IO notification error") }) }))', ../src/libcore/result.rs:746
thread 'IO Worker #2' panicked at 'Error updating discovery registration: Io(Mio(Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("Network IO notification error") }) }))', ../src/libcore/result.rs:746
   1:     0x5647b0facbd0 - sys::backtrace::tracing::imp::write::h1df2fc52f5a1077eehv
   2:     0x5647b0fb0deb - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44584
   3:     0x5647b0fb0a58 - panicking::default_handler::hdd51c136086dc3e0CWz
   4:     0x5647b0f981dc - sys_common::unwind::begin_unwind_inner::h3a281a3586db30a7x5t
   5:     0x5647b0f98668 - sys_common::unwind::begin_unwind_fmt::heafd13fa24ecdc24D4t
   6:     0x5647b0fac041 - rust_begin_unwind
   7:     0x5647b0fe060f - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x5647b0bac9b3 - result::unwrap_failed::h5284585419315112250
   9:     0x5647b0bdf736 - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::stream_writable::h11996765965358868213
  10:     0x5647b0bc7830 - sys_common::unwind::try::try_fn::h10698231780134667756
  11:     0x5647b0fabfcb - __rust_try
  12:     0x5647b0fa757d - sys_common::unwind::inner_try::h6de88a54d8fb341cz2t
  13:     0x5647b0bc8d30 - boxed::F.FnBox<A>::call_box::h5349811147428443626
  14:     0x5647b0faf969 - sys::thread::Thread::new::thread_start::ha2764ce591c12364WTy
  15:     0x7fbd44c436a9 - start_thread
  16:     0x7fbd457eee9c - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x5647b0facbd0 - sys::backtrace::tracing::imp::write::h1df2fc52f5a1077eehv
   2:     0x5647b0fb0deb - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44584
   3:     0x5647b0fb0a58 - panicking::default_handler::hdd51c136086dc3e0CWz
   4:     0x5647b0f981dc - sys_common::unwind::begin_unwind_inner::h3a281a3586db30a7x5t
   5:     0x5647b0f98668 - sys_common::unwind::begin_unwind_fmt::heafd13fa24ecdc24D4t
   6:     0x5647b0fac041 - rust_begin_unwind
   7:     0x5647b0fe060f - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x5647b0bac9b3 - result::unwrap_failed::h5284585419315112250
   9:     0x5647b0bddfc1 - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::stream_readable::h13760410499104460957
  10:     0x5647b0bc78c6 - sys_common::unwind::try::try_fn::h10698231780134667756
  11:     0x5647b0fabfcb - __rust_try
  12:     0x5647b0fa757d - sys_common::unwind::inner_try::h6de88a54d8fb341cz2t
  13:     0x5647b0bc8d30 - boxed::F.FnBox<A>::call_box::h5349811147428443626
  14:     0x5647b0faf969 - sys::thread::Thread::new::thread_start::ha2764ce591c12364WTy
  15:     0x7fbd44c436a9 - start_thread
  16:     0x7fbd457eee9c - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x5647b0facbd0 - sys::backtrace::tracing::imp::write::h1df2fc52f5a1077eehv
   2:     0x5647b0fb0deb - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44584
   3:     0x5647b0fb0a58 - panicking::default_handler::hdd51c136086dc3e0CWz
   4:     0x5647b0f981dc - sys_common::unwind::begin_unwind_inner::h3a281a3586db30a7x5t
   5:     0x5647b0f98668 - sys_common::unwind::begin_unwind_fmt::heafd13fa24ecdc24D4t
   6:     0x5647b0fac041 - rust_begin_unwind
   7:     0x5647b0fe060f - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x5647b0bac9b3 - result::unwrap_failed::h5284585419315112250
   9:     0x5647b0bdf736 - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::stream_writable::h11996765965358868213
  10:     0x5647b0bc7830 - sys_common::unwind::try::try_fn::h10698231780134667756
  11:     0x5647b0fabfcb - __rust_try
  12:     0x5647b0fa757d - sys_common::unwind::inner_try::h6de88a54d8fb341cz2t
  13:     0x5647b0bc8d30 - boxed::F.FnBox<A>::call_box::h5349811147428443626
  14:     0x5647b0faf969 - sys::thread::Thread::new::thread_start::ha2764ce591c12364WTy
  15:     0x7fbd44c436a9 - start_thread
  16:     0x7fbd457eee9c - clone
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x5647b0facbd0 - sys::backtrace::tracing::imp::write::h1df2fc52f5a1077eehv
   2:     0x5647b0fb0deb - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44584
   3:     0x5647b0fb0a58 - panicking::default_handler::hdd51c136086dc3e0CWz
   4:     0x5647b0f981dc - sys_common::unwind::begin_unwind_inner::h3a281a3586db30a7x5t
   5:     0x5647b0f98668 - sys_common::unwind::begin_unwind_fmt::heafd13fa24ecdc24D4t
   6:     0x5647b0fac041 - rust_begin_unwind
   7:     0x5647b0fe060f - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x5647b0bac9b3 - result::unwrap_failed::h5284585419315112250
   9:     0x5647b0bdf736 - network::host::Host<Message>.IoHandler<NetworkIoMessage<Message>>::stream_writable::h11996765965358868213
  10:     0x5647b0bc7830 - sys_common::unwind::try::try_fn::h10698231780134667756
  11:     0x5647b0fabfcb - __rust_try
  12:     0x5647b0fa757d - sys_common::unwind::inner_try::h6de88a54d8fb341cz2t
  13:     0x5647b0bc8d30 - boxed::F.FnBox<A>::call_box::h5349811147428443626
  14:     0x5647b0faf969 - sys::thread::Thread::new::thread_start::ha2764ce591c12364WTy
  15:     0x7fbd44c436a9 - start_thread
  16:     0x7fbd457eee9c - clone
  17:                0x0 - <unknown>
```

**Comment by arkpar** [comment]
Some IO messages are left in the queue on shutdown. Need to fix the shutdown order: clear the queue first, then the event loop

**Comment by xiaods** [comment]
`UTC Error sending network IO message: Mio(Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("Network IO notification error") }) })  `

Parity/v1.9.4-beta-6f21a32-20180228/x86_64-linux-gnu/rustc1.24.0
